//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis.ExportRadniNalog {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExportRadniNalog.IExportRadniNalogWebServis")]
    public interface IExportRadniNalogWebServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportRadniNalogWebServis/ExportRadniNalog", ReplyAction="http://tempuri.org/IExportRadniNalogWebServis/ExportRadniNalogResponse")]
        void ExportRadniNalog(int radniNalogId, string[] radniNalog, int radnikId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExportRadniNalogWebServisChannel : Servis.ExportRadniNalog.IExportRadniNalogWebServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportRadniNalogWebServisClient : System.ServiceModel.ClientBase<Servis.ExportRadniNalog.IExportRadniNalogWebServis>, Servis.ExportRadniNalog.IExportRadniNalogWebServis {
        
        public ExportRadniNalogWebServisClient() {
        }
        
        public ExportRadniNalogWebServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportRadniNalogWebServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportRadniNalogWebServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportRadniNalogWebServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ExportRadniNalog(int radniNalogId, string[] radniNalog, int radnikId) {
            base.Channel.ExportRadniNalog(radniNalogId, radniNalog, radnikId);
        }
    }
}
