//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=LavAuto_old;Integrated Security=True")]
        public string KonekcioniString {
            get {
                return ((string)(this["KonekcioniString"]));
            }
            set {
                this["KonekcioniString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruMesto {
            get {
                return ((bool)(this["AutomatskiDodeliSifruMesto"]));
            }
            set {
                this["AutomatskiDodeliSifruMesto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruRadnik {
            get {
                return ((bool)(this["AutomatskiDodeliSifruRadnik"]));
            }
            set {
                this["AutomatskiDodeliSifruRadnik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruFizickoLice {
            get {
                return ((bool)(this["AutomatskiDodeliSifruFizickoLice"]));
            }
            set {
                this["AutomatskiDodeliSifruFizickoLice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruNacinZahtevaZaPonudu {
            get {
                return ((bool)(this["AutomatskiDodeliSifruNacinZahtevaZaPonudu"]));
            }
            set {
                this["AutomatskiDodeliSifruNacinZahtevaZaPonudu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruNosilacGrupe {
            get {
                return ((bool)(this["AutomatskiDodeliSifruNosilacGrupe"]));
            }
            set {
                this["AutomatskiDodeliSifruNosilacGrupe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruRadnoMesto {
            get {
                return ((bool)(this["AutomatskiDodeliSifruRadnoMesto"]));
            }
            set {
                this["AutomatskiDodeliSifruRadnoMesto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruRadniNalogStatus {
            get {
                return ((bool)(this["AutomatskiDodeliSifruRadniNalogStatus"]));
            }
            set {
                this["AutomatskiDodeliSifruRadniNalogStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruBod {
            get {
                return ((bool)(this["AutomatskiDodeliSifruBod"]));
            }
            set {
                this["AutomatskiDodeliSifruBod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruPoslovniPartner {
            get {
                return ((bool)(this["AutomatskiDodeliSifruPoslovniPartner"]));
            }
            set {
                this["AutomatskiDodeliSifruPoslovniPartner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruUsluga {
            get {
                return ((bool)(this["AutomatskiDodeliSifruUsluga"]));
            }
            set {
                this["AutomatskiDodeliSifruUsluga"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruServisnaKnjizica {
            get {
                return ((bool)(this["AutomatskiDodeliSifruServisnaKnjizica"]));
            }
            set {
                this["AutomatskiDodeliSifruServisnaKnjizica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection DesetPoslednjihUspesnihPretraga {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DesetPoslednjihUspesnihPretraga"]));
            }
            set {
                this["DesetPoslednjihUspesnihPretraga"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruVrstaUsluge {
            get {
                return ((bool)(this["AutomatskiDodeliSifruVrstaUsluge"]));
            }
            set {
                this["AutomatskiDodeliSifruVrstaUsluge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomatskiDodeliSifruNivo {
            get {
                return ((bool)(this["AutomatskiDodeliSifruNivo"]));
            }
            set {
                this["AutomatskiDodeliSifruNivo"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=LavAuto_old;Integrated Security=True")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
    }
}
