<?xml version="1.0" encoding="utf-8"?>
<Database Name="LavAuto" Class="LavAutoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=LavAuto;Integrated Security=True" SettingsObjectName="Baza.Properties.Settings" SettingsPropertyName="LavAutoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Radnik" Member="Radniks">
    <Type Name="Radnik">
      <Column Name="Radnik_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Ime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Prezime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImeOca" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Nadimak" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="JMBG" Type="System.Int64" DbType="BigInt" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DatumRodjenja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Mesto_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Adresa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ZaposlenOd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Raspored" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Radnik_VezaRadnikKorisnickiNalog" Member="VezaRadnikKorisnickiNalogs" ThisKey="Radnik_ID" OtherKey="Radnik_ID" Type="VezaRadnikKorisnickiNalog" />
      <Association Name="Radnik_Ponuda" Member="Ponudas" ThisKey="Radnik_ID" OtherKey="Radnik_ID" Type="Ponuda" />
      <Association Name="Radnik_RadniNalog" Member="RadniNalogs" ThisKey="Radnik_ID" OtherKey="Radnik_ID" Type="RadniNalog" />
      <Association Name="Radnik_StavkaUslugaRadniRaspored" Member="StavkaUslugaRadniRasporeds" ThisKey="Radnik_ID" OtherKey="Radnik_ID" Type="StavkaUslugaRadniRaspored" />
      <Association Name="Mesto_Radnik" Member="Mesto" ThisKey="Mesto_ID" OtherKey="Mesto_ID" Type="Mesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VezaRadnikKorisnickiNalog" Member="VezaRadnikKorisnickiNalogs">
    <Type Name="VezaRadnikKorisnickiNalog">
      <Column Name="Radnik_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KorisnickiNalog" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Radnik_VezaRadnikKorisnickiNalog" Member="Radnik" ThisKey="Radnik_ID" OtherKey="Radnik_ID" Type="Radnik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mesto" Member="Mestos">
    <Type Name="Mesto">
      <Column Name="Mesto_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PozivniBroj" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PostanskiBroj" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Mesto_Radnik" Member="Radniks" ThisKey="Mesto_ID" OtherKey="Mesto_ID" Type="Radnik" />
      <Association Name="Mesto_FizickoLice" Member="FizickoLices" ThisKey="Mesto_ID" OtherKey="Mesto_ID" Type="FizickoLice" />
      <Association Name="Mesto_PoslovniPartner" Member="PoslovniPartners" ThisKey="Mesto_ID" OtherKey="Mesto_ID" Type="PoslovniPartner" />
      <Association Name="Mesto_KorisnikPrograma" Member="KorisnikProgramas" ThisKey="Mesto_ID" OtherKey="Mesto_ID" Type="KorisnikPrograma" />
    </Type>
  </Table>
  <Table Name="dbo.FizickoLice" Member="FizickoLices">
    <Type Name="FizickoLice">
      <Column Name="FizickoLice_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Ime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Prezime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RegistrovanKupac" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Mesto_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Adresa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EMail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="FizickoLice_ServisnaKnjizica" Member="ServisnaKnjizicas" ThisKey="FizickoLice_ID" OtherKey="FizickoLice_ID" Type="ServisnaKnjizica" />
      <Association Name="Mesto_FizickoLice" Member="Mesto" ThisKey="Mesto_ID" OtherKey="Mesto_ID" Type="Mesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PoslovniPartner" Member="PoslovniPartners">
    <Type Name="PoslovniPartner">
      <Column Name="PoslovniPartner_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SkracenNaziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PunNaziv" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PIB" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MaticniBroj" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ZiroRacun" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Mesto_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Adresa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="KontaktOsoba1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Telefon1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EMail1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="KontaktOsoba2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Telefon2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EMail2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Faks" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="PoslovniPartner_ServisnaKnjizica" Member="ServisnaKnjizicas" ThisKey="PoslovniPartner_ID" OtherKey="PoslovniPartner_ID" Type="ServisnaKnjizica" />
      <Association Name="PoslovniPartner_VezaArtikalDobavljac" Member="VezaArtikalDobavljacs" ThisKey="PoslovniPartner_ID" OtherKey="PoslovniPartner_ID" Type="VezaArtikalDobavljac" />
      <Association Name="Mesto_PoslovniPartner" Member="Mesto" ThisKey="Mesto_ID" OtherKey="Mesto_ID" Type="Mesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KorisnikPrograma" Member="KorisnikProgramas">
    <Type Name="KorisnikPrograma">
      <Column Name="KorisnikPrograma_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PIB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MaticniBroj" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ZiroRacun" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Mesto_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Adresa" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Faks" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EMail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="KorisnikPrograma_VezaArtikalDobavljac" Member="VezaArtikalDobavljacs" ThisKey="KorisnikPrograma_ID" OtherKey="KorisnikPrograma_ID" Type="VezaArtikalDobavljac" />
      <Association Name="KorisnikPrograma_Zaglavlje" Member="Zaglavljes" ThisKey="KorisnikPrograma_ID" OtherKey="KorisnikPrograma_ID" Type="Zaglavlje" />
      <Association Name="Mesto_KorisnikPrograma" Member="Mesto" ThisKey="Mesto_ID" OtherKey="Mesto_ID" Type="Mesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServisnaKnjizica" Member="ServisnaKnjizicas">
    <Type Name="ServisnaKnjizica">
      <Column Name="ServisnaKnjizica_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FizickoLice_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PoslovniPartner_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TipAutomobila_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BrojSasije" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BrojMotora" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Godiste" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Kilometraza" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RegistarskiBroj" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DatumRegistracije" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ABS" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PS" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AC" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Napomena" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ServisnaKnjizica_Zaglavlje" Member="Zaglavljes" ThisKey="ServisnaKnjizica_ID" OtherKey="ServisnaKnjizica_ID" Type="Zaglavlje" />
      <Association Name="FizickoLice_ServisnaKnjizica" Member="FizickoLice" ThisKey="FizickoLice_ID" OtherKey="FizickoLice_ID" Type="FizickoLice" IsForeignKey="true" />
      <Association Name="PoslovniPartner_ServisnaKnjizica" Member="PoslovniPartner" ThisKey="PoslovniPartner_ID" OtherKey="PoslovniPartner_ID" Type="PoslovniPartner" IsForeignKey="true" />
      <Association Name="TipAutomobila_ServisnaKnjizica" Member="TipAutomobila" ThisKey="TipAutomobila_ID" OtherKey="TipAutomobila_ID" Type="TipAutomobila" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipAutomobila" Member="TipAutomobilas">
    <Type Name="TipAutomobila">
      <Column Name="TipAutomobila_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Opis_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModelAutomobila_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProizvodnjaOd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProizvodnjaDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SnagaKWOd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SnagaKWDo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SnagaKSOd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SnagaKSDo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ZapreminaCcm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cilindara" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="VentilaPoCilindru" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="VrstaMotora_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VrstaGoriva_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PripremaGoriva_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VrstaKatalizatora_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NaponAkumulatora_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VrstaKaroserije_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vrata" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="RezervoarLitara" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ABS_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ASR_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KocioniSistem_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VrstaKocnica_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VrstaPogona_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Menjac_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TipAutomobila_ServisnaKnjizica" Member="ServisnaKnjizicas" ThisKey="TipAutomobila_ID" OtherKey="TipAutomobila_ID" Type="ServisnaKnjizica" />
      <Association Name="TipAutomobila_VezaTipAutomobilaMotor" Member="VezaTipAutomobilaMotors" ThisKey="TipAutomobila_ID" OtherKey="TipAutomobila_ID" Type="VezaTipAutomobilaMotor" />
      <Association Name="TipAutomobila_Ugradnja" Member="Ugradnjas" ThisKey="TipAutomobila_ID" OtherKey="TipAutomobila_ID" Type="Ugradnja" />
      <Association Name="ModelAutomobila_TipAutomobila" Member="ModelAutomobila" ThisKey="ModelAutomobila_ID" OtherKey="ModelAutomobila_ID" Type="ModelAutomobila" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila" Member="OpisTabela" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila1" Member="OpisTabelaMenjac_Opis" ThisKey="Menjac_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila2" Member="OpisTabelaPripremaGoriva_Opis" ThisKey="PripremaGoriva_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila3" Member="OpisTabelaABS_Opis" ThisKey="ABS_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila4" Member="OpisTabelaKocioniSistem_Opis" ThisKey="KocioniSistem_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila5" Member="OpisTabelaNaponAkumulatora_Opis" ThisKey="NaponAkumulatora_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila6" Member="OpisTabelaASR_Opis" ThisKey="ASR_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila7" Member="OpisTabelaVrstaMotora_Opis" ThisKey="VrstaMotora_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila8" Member="OpisTabelaVrstaKocnica_Opis" ThisKey="VrstaKocnica_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila9" Member="OpisTabelaVrstaGoriva_Opis" ThisKey="VrstaGoriva_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila10" Member="OpisTabelaVrstaKatalizatora_Opis" ThisKey="VrstaKatalizatora_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila11" Member="OpisTabelaVrstaKaroserije_Opis" ThisKey="VrstaKaroserije_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_TipAutomobila12" Member="OpisTabelaVrstaPogona_Opis" ThisKey="VrstaPogona_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ModelAutomobila" Member="ModelAutomobilas">
    <Type Name="ModelAutomobila">
      <Column Name="ModelAutomobila_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Opis_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Proizvodjac_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ProizvodnjaOd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProizvodnjaDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ModelAutomobila_TipAutomobila" Member="TipAutomobilas" ThisKey="ModelAutomobila_ID" OtherKey="ModelAutomobila_ID" Type="TipAutomobila" />
      <Association Name="Proizvodjac_ModelAutomobila" Member="Proizvodjac" ThisKey="Proizvodjac_ID" OtherKey="Proizvodjac_ID" Type="Proizvodjac" IsForeignKey="true" />
      <Association Name="OpisTabela_ModelAutomobila" Member="OpisTabela" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proizvodjac" Member="Proizvodjacs">
    <Type Name="Proizvodjac">
      <Column Name="Proizvodjac_ID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Proizvodjac_ModelAutomobila" Member="ModelAutomobilas" ThisKey="Proizvodjac_ID" OtherKey="Proizvodjac_ID" Type="ModelAutomobila" />
      <Association Name="Proizvodjac_Artikal" Member="Artikals" ThisKey="Proizvodjac_ID" OtherKey="Proizvodjac_ID" Type="Artikal" />
      <Association Name="Proizvodjac_Motor" Member="Motors" ThisKey="Proizvodjac_ID" OtherKey="Proizvodjac_ID" Type="Motor" />
      <Association Name="Proizvodjac_VezaArtikalBrojZaPretragu" Member="VezaArtikalBrojZaPretragus" ThisKey="Proizvodjac_ID" OtherKey="Proizvodjac_ID" Type="VezaArtikalBrojZaPretragu" />
    </Type>
  </Table>
  <Table Name="dbo.Artikal" Member="Artikals">
    <Type Name="Artikal">
      <Column Name="Artikal_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Opis_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BrojProizvodjaca" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Proizvodjac_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PoreskaStopa_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Artikal_VezaArtikalStablo" Member="VezaArtikalStablos" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="VezaArtikalStablo" />
      <Association Name="Artikal_VezaArtikalKriterijum" Member="VezaArtikalKriterijums" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="VezaArtikalKriterijum" />
      <Association Name="Artikal_Ugradnja" Member="Ugradnjas" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="Ugradnja" />
      <Association Name="Artikal_VezaArtikalBrojZaPretragu" Member="VezaArtikalBrojZaPretragus" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="VezaArtikalBrojZaPretragu" />
      <Association Name="Artikal_VezaArtikalDobavljac" Member="VezaArtikalDobavljacs" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="VezaArtikalDobavljac" />
      <Association Name="Proizvodjac_Artikal" Member="Proizvodjac" ThisKey="Proizvodjac_ID" OtherKey="Proizvodjac_ID" Type="Proizvodjac" IsForeignKey="true" />
      <Association Name="PoreskaStopa_Artikal" Member="PoreskaStopa" ThisKey="PoreskaStopa_ID" OtherKey="PoreskaStopa_ID" Type="PoreskaStopa" IsForeignKey="true" />
      <Association Name="OpisTabela_Artikal" Member="OpisTabela" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Stablo" Member="Stablos">
    <Type Name="Stablo">
      <Column Name="Stablo_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Opis_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Roditelj_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nivo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="TipCvora_ID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Stablo_Stablo" Member="Stablos" ThisKey="Stablo_ID" OtherKey="Roditelj_ID" Type="Stablo" />
      <Association Name="Stablo_VezaArtikalStablo" Member="VezaArtikalStablos" ThisKey="Stablo_ID" OtherKey="Stablo_ID" Type="VezaArtikalStablo" />
      <Association Name="Stablo_Stablo" Member="Stablo1" ThisKey="Roditelj_ID" OtherKey="Stablo_ID" Type="Stablo" IsForeignKey="true" />
      <Association Name="TipCvora_Stablo" Member="TipCvora" ThisKey="TipCvora_ID" OtherKey="TipCvora_ID" Type="TipCvora" IsForeignKey="true" />
      <Association Name="OpisTabela_Stablo" Member="OpisTabela" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VezaArtikalStablo" Member="VezaArtikalStablos">
    <Type Name="VezaArtikalStablo">
      <Column Name="Artikal_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Stablo_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Artikal_VezaArtikalStablo" Member="Artikal" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="Artikal" IsForeignKey="true" />
      <Association Name="Stablo_VezaArtikalStablo" Member="Stablo" ThisKey="Stablo_ID" OtherKey="Stablo_ID" Type="Stablo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VezaArtikalKriterijum" Member="VezaArtikalKriterijums">
    <Type Name="VezaArtikalKriterijum">
      <Column Name="VezaArtikalKriterijum_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Artikal_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Kriterijum_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Vrednost" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Opis_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Artikal_VezaArtikalKriterijum" Member="Artikal" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="Artikal" IsForeignKey="true" />
      <Association Name="Kriterijum_VezaArtikalKriterijum" Member="Kriterijum" ThisKey="Kriterijum_ID" OtherKey="Kriterijum_ID" Type="Kriterijum" IsForeignKey="true" />
      <Association Name="OpisTabela_VezaArtikalKriterijum" Member="OpisTabela" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kriterijum" Member="Kriterijums">
    <Type Name="Kriterijum">
      <Column Name="Kriterijum_ID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Opis_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kriterijum_VezaArtikalKriterijum" Member="VezaArtikalKriterijums" ThisKey="Kriterijum_ID" OtherKey="Kriterijum_ID" Type="VezaArtikalKriterijum" />
      <Association Name="Kriterijum_VezaUgradnjaKriterijum" Member="VezaUgradnjaKriterijums" ThisKey="Kriterijum_ID" OtherKey="Kriterijum_ID" Type="VezaUgradnjaKriterijum" />
      <Association Name="OpisTabela_Kriterijum" Member="OpisTabela" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Motor" Member="Motors">
    <Type Name="Motor">
      <Column Name="Motor_ID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Oznaka" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Proizvodjac_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ProizvodnjaOd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProizvodnjaDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SnagaKwKodObrtajaUMinutiOd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SnagaKwKodObrtajaUMinutiDo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ObrtajaUMinutiKodSnageKwOd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ObrtajaUMinutiKodSnageKwDo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ObrtniMomenatKodObrtajaUMinutiOd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ObrtajaUMinutiKodObrtnogMomentaOd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ObrtniMomenatKodObrtajaUMinutiDo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ObrtajaUMinutiKodObrtnogMomentaDo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SnagaKSOd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SnagaKSDo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ZapreminaCcmOd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZapreminaCcmDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cilindara" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="PrecnikCilindra" Type="System.Decimal" DbType="Decimal(6,3)" CanBeNull="true" />
      <Column Name="OblikGlaveCilindra_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Korak" Type="System.Decimal" DbType="Decimal(6,3)" CanBeNull="true" />
      <Column Name="BrojLezajevaKolenastogVratilaRadilice" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="KompresijaOd" Type="System.Decimal" DbType="Decimal(6,3)" CanBeNull="true" />
      <Column Name="KompresijaDo" Type="System.Decimal" DbType="Decimal(6,3)" CanBeNull="true" />
      <Column Name="Ventila" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="UpravljanjeVentilima_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VrstaMotora_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VrstaGoriva_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PripremaGoriva_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PunjenjeKompresija_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StandardIzduvnihGasova_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpravljanjeMotorom_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OblikBlokaMotora_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VrstaHladjenja_Opis" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Motor_VezaTipAutomobilaMotor" Member="VezaTipAutomobilaMotors" ThisKey="Motor_ID" OtherKey="Motor_ID" Type="VezaTipAutomobilaMotor" />
      <Association Name="Proizvodjac_Motor" Member="Proizvodjac" ThisKey="Proizvodjac_ID" OtherKey="Proizvodjac_ID" Type="Proizvodjac" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor" Member="OpisTabelaOblikBlokaMotora_Opis" ThisKey="OblikBlokaMotora_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor1" Member="OpisTabelaVrstaHladjenja_Opis" ThisKey="VrstaHladjenja_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor2" Member="OpisTabelaVrstaGoriva_Opis" ThisKey="VrstaGoriva_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor3" Member="OpisTabelaPripremaGoriva_Opis" ThisKey="PripremaGoriva_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor4" Member="OpisTabelaVrstaMotora_Opis" ThisKey="VrstaMotora_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor5" Member="OpisTabelaPunjenjeKompresija_Opis" ThisKey="PunjenjeKompresija_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor6" Member="OpisTabelaStandardIzduvnihGasova_Opis" ThisKey="StandardIzduvnihGasova_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor7" Member="OpisTabelaOblikGlaveCilindra_Opis" ThisKey="OblikGlaveCilindra_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor8" Member="OpisTabelaUpravljanjeMotorom_Opis" ThisKey="UpravljanjeMotorom_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
      <Association Name="OpisTabela_Motor9" Member="OpisTabelaUpravljanjeVentilima_Opis" ThisKey="UpravljanjeVentilima_Opis" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VezaTipAutomobilaMotor" Member="VezaTipAutomobilaMotors">
    <Type Name="VezaTipAutomobilaMotor">
      <Column Name="TipAutomobila_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Motor_ID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UgradnjaOd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UgradnjaDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Motor_VezaTipAutomobilaMotor" Member="Motor" ThisKey="Motor_ID" OtherKey="Motor_ID" Type="Motor" IsForeignKey="true" />
      <Association Name="TipAutomobila_VezaTipAutomobilaMotor" Member="TipAutomobila" ThisKey="TipAutomobila_ID" OtherKey="TipAutomobila_ID" Type="TipAutomobila" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PoreskaStopa" Member="PoreskaStopas">
    <Type Name="PoreskaStopa">
      <Column Name="PoreskaStopa_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VrednostProcenata" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="PoreskaStopa_Artikal" Member="Artikals" ThisKey="PoreskaStopa_ID" OtherKey="PoreskaStopa_ID" Type="Artikal" />
      <Association Name="PoreskaStopa_StavkaUsluga" Member="StavkaUslugas" ThisKey="PoreskaStopa_ID" OtherKey="UslugaPoreskaStopa_ID" Type="StavkaUsluga" />
      <Association Name="PoreskaStopa_StavkaArtikal" Member="StavkaArtikals" ThisKey="PoreskaStopa_ID" OtherKey="ArtikalPoreskaStopa_ID" Type="StavkaArtikal" />
      <Association Name="PoreskaStopa_Usluga" Member="Uslugas" ThisKey="PoreskaStopa_ID" OtherKey="PoreskaStopa_ID" Type="Usluga" />
    </Type>
  </Table>
  <Table Name="dbo.Ugradnja" Member="Ugradnjas">
    <Type Name="Ugradnja">
      <Column Name="Artikal_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TipAutomobila_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Ugradnja_VezaUgradnjaKriterijum" Member="VezaUgradnjaKriterijums" ThisKey="Artikal_ID,TipAutomobila_ID" OtherKey="UgradnjaArtikal_ID,UgradnjaTipAutomobila_ID" Type="VezaUgradnjaKriterijum" />
      <Association Name="Artikal_Ugradnja" Member="Artikal" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="Artikal" IsForeignKey="true" />
      <Association Name="TipAutomobila_Ugradnja" Member="TipAutomobila" ThisKey="TipAutomobila_ID" OtherKey="TipAutomobila_ID" Type="TipAutomobila" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VezaUgradnjaKriterijum" Member="VezaUgradnjaKriterijums">
    <Type Name="VezaUgradnjaKriterijum">
      <Column Name="VezaUgradnjaKriterijum_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UgradnjaArtikal_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UgradnjaTipAutomobila_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Kriterijum_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Vrednost" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Opis_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Kriterijum_VezaUgradnjaKriterijum" Member="Kriterijum" ThisKey="Kriterijum_ID" OtherKey="Kriterijum_ID" Type="Kriterijum" IsForeignKey="true" />
      <Association Name="Ugradnja_VezaUgradnjaKriterijum" Member="Ugradnja" ThisKey="UgradnjaArtikal_ID,UgradnjaTipAutomobila_ID" OtherKey="Artikal_ID,TipAutomobila_ID" Type="Ugradnja" IsForeignKey="true" />
      <Association Name="OpisTabela_VezaUgradnjaKriterijum" Member="OpisTabela" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="OpisTabela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VrstaBrojaZaPretragu" Member="VrstaBrojaZaPretragus">
    <Type Name="VrstaBrojaZaPretragu">
      <Column Name="VrstaBrojaZaPretragu_ID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="VrstaBrojaZaPretragu_VezaArtikalBrojZaPretragu" Member="VezaArtikalBrojZaPretragus" ThisKey="VrstaBrojaZaPretragu_ID" OtherKey="VrstaBrojaZaPretragu_ID" Type="VezaArtikalBrojZaPretragu" />
    </Type>
  </Table>
  <Table Name="dbo.VezaArtikalBrojZaPretragu" Member="VezaArtikalBrojZaPretragus">
    <Type Name="VezaArtikalBrojZaPretragu">
      <Column Name="VezaArtikalBrojZaPretragu_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Artikal_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BrojZaPretragu" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BrojZaPrikazivanje" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VrstaBrojaZaPretragu_ID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Proizvodjac_ID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Artikal_VezaArtikalBrojZaPretragu" Member="Artikal" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="Artikal" IsForeignKey="true" />
      <Association Name="Proizvodjac_VezaArtikalBrojZaPretragu" Member="Proizvodjac" ThisKey="Proizvodjac_ID" OtherKey="Proizvodjac_ID" Type="Proizvodjac" IsForeignKey="true" />
      <Association Name="VrstaBrojaZaPretragu_VezaArtikalBrojZaPretragu" Member="VrstaBrojaZaPretragu" ThisKey="VrstaBrojaZaPretragu_ID" OtherKey="VrstaBrojaZaPretragu_ID" Type="VrstaBrojaZaPretragu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VezaArtikalDobavljac" Member="VezaArtikalDobavljacs">
    <Type Name="VezaArtikalDobavljac">
      <Column Name="VezaArtikalDobavljac_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PoslovniPartner_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="KorisnikPrograma_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Artikal_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CenaBezPoreza" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DatumAzuriranja" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="KolicinaNaStanju" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="VezaArtikalDobavljac_StavkaArtikal" Member="StavkaArtikals" ThisKey="VezaArtikalDobavljac_ID" OtherKey="VezaArtikalDobavljac_ID" Type="StavkaArtikal" />
      <Association Name="PoslovniPartner_VezaArtikalDobavljac" Member="PoslovniPartner" ThisKey="PoslovniPartner_ID" OtherKey="PoslovniPartner_ID" Type="PoslovniPartner" IsForeignKey="true" />
      <Association Name="Artikal_VezaArtikalDobavljac" Member="Artikal" ThisKey="Artikal_ID" OtherKey="Artikal_ID" Type="Artikal" IsForeignKey="true" />
      <Association Name="KorisnikPrograma_VezaArtikalDobavljac" Member="KorisnikPrograma" ThisKey="KorisnikPrograma_ID" OtherKey="KorisnikPrograma_ID" Type="KorisnikPrograma" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipCvora" Member="TipCvoras">
    <Type Name="TipCvora">
      <Column Name="TipCvora_ID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="TipCvora_Stablo" Member="Stablos" ThisKey="TipCvora_ID" OtherKey="TipCvora_ID" Type="Stablo" />
    </Type>
  </Table>
  <Table Name="dbo.Opis" Member="OpisTabelas">
    <Type Name="OpisTabela">
      <Column Name="Opis_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="OpisTabela_TipAutomobila" Member="TipAutomobilas" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila1" Member="TipAutomobilas1" ThisKey="Opis_ID" OtherKey="Menjac_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila2" Member="TipAutomobilas2" ThisKey="Opis_ID" OtherKey="PripremaGoriva_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila3" Member="TipAutomobilas3" ThisKey="Opis_ID" OtherKey="ABS_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila4" Member="TipAutomobilas4" ThisKey="Opis_ID" OtherKey="KocioniSistem_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila5" Member="TipAutomobilas5" ThisKey="Opis_ID" OtherKey="NaponAkumulatora_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila6" Member="TipAutomobilas6" ThisKey="Opis_ID" OtherKey="ASR_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila7" Member="TipAutomobilas7" ThisKey="Opis_ID" OtherKey="VrstaMotora_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila8" Member="TipAutomobilas8" ThisKey="Opis_ID" OtherKey="VrstaKocnica_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila9" Member="TipAutomobilas9" ThisKey="Opis_ID" OtherKey="VrstaGoriva_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila10" Member="TipAutomobilas10" ThisKey="Opis_ID" OtherKey="VrstaKatalizatora_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila11" Member="TipAutomobilas11" ThisKey="Opis_ID" OtherKey="VrstaKaroserije_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_TipAutomobila12" Member="TipAutomobilas12" ThisKey="Opis_ID" OtherKey="VrstaPogona_Opis" Type="TipAutomobila" />
      <Association Name="OpisTabela_ModelAutomobila" Member="ModelAutomobilas" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="ModelAutomobila" />
      <Association Name="OpisTabela_Artikal" Member="Artikals" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="Artikal" />
      <Association Name="OpisTabela_Stablo" Member="Stablos" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="Stablo" />
      <Association Name="OpisTabela_VezaArtikalKriterijum" Member="VezaArtikalKriterijums" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="VezaArtikalKriterijum" />
      <Association Name="OpisTabela_Kriterijum" Member="Kriterijums" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="Kriterijum" />
      <Association Name="OpisTabela_Motor" Member="Motors" ThisKey="Opis_ID" OtherKey="OblikBlokaMotora_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor1" Member="Motors1" ThisKey="Opis_ID" OtherKey="VrstaHladjenja_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor2" Member="Motors2" ThisKey="Opis_ID" OtherKey="VrstaGoriva_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor3" Member="Motors3" ThisKey="Opis_ID" OtherKey="PripremaGoriva_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor4" Member="Motors4" ThisKey="Opis_ID" OtherKey="VrstaMotora_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor5" Member="Motors5" ThisKey="Opis_ID" OtherKey="PunjenjeKompresija_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor6" Member="Motors6" ThisKey="Opis_ID" OtherKey="StandardIzduvnihGasova_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor7" Member="Motors7" ThisKey="Opis_ID" OtherKey="OblikGlaveCilindra_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor8" Member="Motors8" ThisKey="Opis_ID" OtherKey="UpravljanjeMotorom_Opis" Type="Motor" />
      <Association Name="OpisTabela_Motor9" Member="Motors9" ThisKey="Opis_ID" OtherKey="UpravljanjeVentilima_Opis" Type="Motor" />
      <Association Name="OpisTabela_VezaUgradnjaKriterijum" Member="VezaUgradnjaKriterijums" ThisKey="Opis_ID" OtherKey="Opis_ID" Type="VezaUgradnjaKriterijum" />
    </Type>
  </Table>
  <Table Name="dbo.Zaglavlje" Member="Zaglavljes">
    <Type Name="Zaglavlje">
      <Column Name="Zaglavlje_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServisnaKnjizica_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="KorisnikPrograma_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VremePromene" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="KorisnickiNalog" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Zaglavlje_Ponuda" Member="Ponuda" ThisKey="Zaglavlje_ID" OtherKey="Ponuda_ID" Type="Ponuda" Cardinality="One" />
      <Association Name="Zaglavlje_RadniNalog" Member="RadniNalog" ThisKey="Zaglavlje_ID" OtherKey="RadniNalog_ID" Type="RadniNalog" Cardinality="One" />
      <Association Name="ServisnaKnjizica_Zaglavlje" Member="ServisnaKnjizica" ThisKey="ServisnaKnjizica_ID" OtherKey="ServisnaKnjizica_ID" Type="ServisnaKnjizica" IsForeignKey="true" />
      <Association Name="KorisnikPrograma_Zaglavlje" Member="KorisnikPrograma" ThisKey="KorisnikPrograma_ID" OtherKey="KorisnikPrograma_ID" Type="KorisnikPrograma" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ponuda" Member="Ponudas">
    <Type Name="Ponuda">
      <Column Name="Ponuda_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Radnik_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Vreme" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NacinZahtevaZaPonudu_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PreuzimaLicno" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PreuzeoLicnoU" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ObavestiTelefonom" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ObavestenTelefonomU" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PosaljiSMSObavestenje" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PoslatoSMSObavestenjeU" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Napomena" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VremePromene" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="KorisnickiNalog" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Ponuda_StavkaUsluga" Member="StavkaUslugas" ThisKey="Ponuda_ID" OtherKey="Ponuda_ID" Type="StavkaUsluga" />
      <Association Name="Radnik_Ponuda" Member="Radnik" ThisKey="Radnik_ID" OtherKey="Radnik_ID" Type="Radnik" IsForeignKey="true" />
      <Association Name="Zaglavlje_Ponuda" Member="Zaglavlje" ThisKey="Ponuda_ID" OtherKey="Zaglavlje_ID" Type="Zaglavlje" IsForeignKey="true" />
      <Association Name="NacinZahtevaZaPonudu_Ponuda" Member="NacinZahtevaZaPonudu" ThisKey="NacinZahtevaZaPonudu_ID" OtherKey="NacinZahtevaZaPonudu_ID" Type="NacinZahtevaZaPonudu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RadniNalog" Member="RadniNalogs">
    <Type Name="RadniNalog">
      <Column Name="RadniNalog_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Radnik_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Vreme" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PotrebnoVreme" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Kilometraza" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RegistarskiBroj" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DatumRegistarcije" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Napomena" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VremePromene" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="KorisnickiNalog" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="RadniNalog_StavkaUsluga" Member="StavkaUslugas" ThisKey="RadniNalog_ID" OtherKey="RadniNalog_ID" Type="StavkaUsluga" />
      <Association Name="Radnik_RadniNalog" Member="Radnik" ThisKey="Radnik_ID" OtherKey="Radnik_ID" Type="Radnik" IsForeignKey="true" />
      <Association Name="Zaglavlje_RadniNalog" Member="Zaglavlje" ThisKey="RadniNalog_ID" OtherKey="Zaglavlje_ID" Type="Zaglavlje" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StavkaUsluga" Member="StavkaUslugas">
    <Type Name="StavkaUsluga">
      <Column Name="StavkaUsluga_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ponuda_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RadniNalog_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Usluga_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UslugaKolicina" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UslugaCenaBezPoreza" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UslugaPoreskaStopa_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VremePromene" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="KorisnickiNalog" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="StavkaUsluga_StavkaArtikal" Member="StavkaArtikals" ThisKey="StavkaUsluga_ID" OtherKey="StavkaUsluga_ID" Type="StavkaArtikal" />
      <Association Name="StavkaUsluga_RadniNalogStavkaUsluga" Member="RadniNalogStavkaUsluga" ThisKey="StavkaUsluga_ID" OtherKey="RadniNalogStavkaUsluga_ID" Type="RadniNalogStavkaUsluga" Cardinality="One" />
      <Association Name="StavkaUsluga_StavkaUslugaRadniRaspored" Member="StavkaUslugaRadniRasporeds" ThisKey="StavkaUsluga_ID" OtherKey="StavkaUsluga_ID" Type="StavkaUslugaRadniRaspored" />
      <Association Name="PoreskaStopa_StavkaUsluga" Member="UslugaPoreskaStopa" Storage="_PoreskaStopa" ThisKey="UslugaPoreskaStopa_ID" OtherKey="PoreskaStopa_ID" Type="PoreskaStopa" IsForeignKey="true" />
      <Association Name="RadniNalog_StavkaUsluga" Member="RadniNalog" ThisKey="RadniNalog_ID" OtherKey="RadniNalog_ID" Type="RadniNalog" IsForeignKey="true" />
      <Association Name="Ponuda_StavkaUsluga" Member="Ponuda" ThisKey="Ponuda_ID" OtherKey="Ponuda_ID" Type="Ponuda" IsForeignKey="true" />
      <Association Name="Usluga_StavkaUsluga" Member="Usluga" ThisKey="Usluga_ID" OtherKey="Usluga_ID" Type="Usluga" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StavkaArtikal" Member="StavkaArtikals">
    <Type Name="StavkaArtikal">
      <Column Name="StavkaArtikal_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StavkaUsluga_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VezaArtikalDobavljac_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ArtikalCenaBezPoreza" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ArtikalKolicina" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ArtikalPoreskaStopa_ID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VremePromene" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="KorisnickiNalog" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="VezaArtikalDobavljac_StavkaArtikal" Member="VezaArtikalDobavljac" ThisKey="VezaArtikalDobavljac_ID" OtherKey="VezaArtikalDobavljac_ID" Type="VezaArtikalDobavljac" IsForeignKey="true" />
      <Association Name="PoreskaStopa_StavkaArtikal" Member="ArtikalPoreskaStopa" Storage="_PoreskaStopa" ThisKey="ArtikalPoreskaStopa_ID" OtherKey="PoreskaStopa_ID" Type="PoreskaStopa" IsForeignKey="true" />
      <Association Name="StavkaUsluga_StavkaArtikal" Member="StavkaUsluga" ThisKey="StavkaUsluga_ID" OtherKey="StavkaUsluga_ID" Type="StavkaUsluga" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RadniNalogStavkaUsluga" Member="RadniNalogStavkaUslugas">
    <Type Name="RadniNalogStavkaUsluga">
      <Column Name="RadniNalogStavkaUsluga_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RadniNalogStatus_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NormaSatiMinuta" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Napomena" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="StavkaUsluga_RadniNalogStavkaUsluga" Member="StavkaUsluga" ThisKey="RadniNalogStavkaUsluga_ID" OtherKey="StavkaUsluga_ID" Type="StavkaUsluga" IsForeignKey="true" />
      <Association Name="RadniNalogStatus_RadniNalogStavkaUsluga" Member="RadniNalogStatus" ThisKey="RadniNalogStatus_ID" OtherKey="RadniNalogStatus_ID" Type="RadniNalogStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usluga" Member="Uslugas">
    <Type Name="Usluga">
      <Column Name="Usluga_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VrstaUsluge_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NosilacGrupe_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Nivo_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NormaSatiMinuta" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BrojBodova" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Bod_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PoreskaStopa_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Usluga_StavkaUsluga" Member="StavkaUslugas" ThisKey="Usluga_ID" OtherKey="Usluga_ID" Type="StavkaUsluga" />
      <Association Name="PoreskaStopa_Usluga" Member="PoreskaStopa" ThisKey="PoreskaStopa_ID" OtherKey="PoreskaStopa_ID" Type="PoreskaStopa" IsForeignKey="true" />
      <Association Name="VrstaUsluge_Usluga" Member="VrstaUsluge" ThisKey="VrstaUsluge_ID" OtherKey="VrstaUsluge_ID" Type="VrstaUsluge" IsForeignKey="true" />
      <Association Name="NosilacGrupe_Usluga" Member="NosilacGrupe" ThisKey="NosilacGrupe_ID" OtherKey="NosilacGrupe_ID" Type="NosilacGrupe" IsForeignKey="true" />
      <Association Name="Nivo_Usluga" Member="Nivo" ThisKey="Nivo_ID" OtherKey="Nivo_ID" Type="Nivo" IsForeignKey="true" />
      <Association Name="Bod_Usluga" Member="Bod" ThisKey="Bod_ID" OtherKey="Bod_ID" Type="Bod" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VrstaUsluge" Member="VrstaUsluges">
    <Type Name="VrstaUsluge">
      <Column Name="VrstaUsluge_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="VrstaUsluge_Usluga" Member="Uslugas" ThisKey="VrstaUsluge_ID" OtherKey="VrstaUsluge_ID" Type="Usluga" />
    </Type>
  </Table>
  <Table Name="dbo.RadnoMesto" Member="RadnoMestos">
    <Type Name="RadnoMesto">
      <Column Name="RadnoMesto_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="RadnoMesto_StavkaUslugaRadniRaspored" Member="StavkaUslugaRadniRasporeds" ThisKey="RadnoMesto_ID" OtherKey="RadnoMesto_ID" Type="StavkaUslugaRadniRaspored" />
    </Type>
  </Table>
  <Table Name="dbo.RadniNalogStatus" Member="RadniNalogStatus">
    <Type Name="RadniNalogStatus">
      <Column Name="RadniNalogStatus_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="RadniNalogStatus_RadniNalogStavkaUsluga" Member="RadniNalogStavkaUslugas" ThisKey="RadniNalogStatus_ID" OtherKey="RadniNalogStatus_ID" Type="RadniNalogStavkaUsluga" />
    </Type>
  </Table>
  <Table Name="dbo.NosilacGrupe" Member="NosilacGrupes">
    <Type Name="NosilacGrupe">
      <Column Name="NosilacGrupe_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="NosilacGrupe_Usluga" Member="Uslugas" ThisKey="NosilacGrupe_ID" OtherKey="NosilacGrupe_ID" Type="Usluga" />
    </Type>
  </Table>
  <Table Name="dbo.Nivo" Member="Nivos">
    <Type Name="Nivo">
      <Column Name="Nivo_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Nivo_Usluga" Member="Uslugas" ThisKey="Nivo_ID" OtherKey="Nivo_ID" Type="Usluga" />
    </Type>
  </Table>
  <Table Name="dbo.NacinZahtevaZaPonudu" Member="NacinZahtevaZaPonudus">
    <Type Name="NacinZahtevaZaPonudu">
      <Column Name="NacinZahtevaZaPonudu_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="NacinZahtevaZaPonudu_Ponuda" Member="Ponudas" ThisKey="NacinZahtevaZaPonudu_ID" OtherKey="NacinZahtevaZaPonudu_ID" Type="Ponuda" />
    </Type>
  </Table>
  <Table Name="dbo.Bod" Member="Bods">
    <Type Name="Bod">
      <Column Name="Bod_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Vrednost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Bod_Usluga" Member="Uslugas" ThisKey="Bod_ID" OtherKey="Bod_ID" Type="Usluga" />
    </Type>
  </Table>
  <Table Name="dbo.RadnoVreme" Member="RadnoVremes">
    <Type Name="RadnoVreme">
      <Column Name="RadnoVreme_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sifra" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PocinjeOd" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="TrajeDo" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Association Name="RadnoVreme_StavkaUslugaRadniRaspored" Member="StavkaUslugaRadniRasporeds" ThisKey="RadnoVreme_ID" OtherKey="RadnoVreme_ID" Type="StavkaUslugaRadniRaspored" />
    </Type>
  </Table>
  <Table Name="dbo.StavkaUslugaRadniRaspored" Member="StavkaUslugaRadniRasporeds">
    <Type Name="StavkaUslugaRadniRaspored">
      <Column Name="StavkaUslugaRadniRaspored_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StavkaUsluga_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Radnik_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RadnoMesto_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RadnoVreme_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="VremePromene" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KorisnickiNalog" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="StavkaUsluga_StavkaUslugaRadniRaspored" Member="StavkaUsluga" ThisKey="StavkaUsluga_ID" OtherKey="StavkaUsluga_ID" Type="StavkaUsluga" IsForeignKey="true" />
      <Association Name="Radnik_StavkaUslugaRadniRaspored" Member="Radnik" ThisKey="Radnik_ID" OtherKey="Radnik_ID" Type="Radnik" IsForeignKey="true" />
      <Association Name="RadnoMesto_StavkaUslugaRadniRaspored" Member="RadnoMesto" ThisKey="RadnoMesto_ID" OtherKey="RadnoMesto_ID" Type="RadnoMesto" IsForeignKey="true" />
      <Association Name="RadnoVreme_StavkaUslugaRadniRaspored" Member="RadnoVreme" ThisKey="RadnoVreme_ID" OtherKey="RadnoVreme_ID" Type="RadnoVreme" IsForeignKey="true" />
    </Type>
  </Table>
</Database>