//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace LAV.DS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ArtikalDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ArtikalDataSet : global::System.Data.DataSet {
        
        private vwVezaArtikalDobavljacDataTable tablevwVezaArtikalDobavljac;
        
        private uspDajBrojacDataTable tableuspDajBrojac;
        
        private vwArtikalDataTable tablevwArtikal;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ArtikalDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected ArtikalDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["vwVezaArtikalDobavljac"] != null)) {
                    base.Tables.Add(new vwVezaArtikalDobavljacDataTable(ds.Tables["vwVezaArtikalDobavljac"]));
                }
                if ((ds.Tables["uspDajBrojac"] != null)) {
                    base.Tables.Add(new uspDajBrojacDataTable(ds.Tables["uspDajBrojac"]));
                }
                if ((ds.Tables["vwArtikal"] != null)) {
                    base.Tables.Add(new vwArtikalDataTable(ds.Tables["vwArtikal"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public vwVezaArtikalDobavljacDataTable vwVezaArtikalDobavljac {
            get {
                return this.tablevwVezaArtikalDobavljac;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public uspDajBrojacDataTable uspDajBrojac {
            get {
                return this.tableuspDajBrojac;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public vwArtikalDataTable vwArtikal {
            get {
                return this.tablevwArtikal;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            ArtikalDataSet cln = ((ArtikalDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["vwVezaArtikalDobavljac"] != null)) {
                    base.Tables.Add(new vwVezaArtikalDobavljacDataTable(ds.Tables["vwVezaArtikalDobavljac"]));
                }
                if ((ds.Tables["uspDajBrojac"] != null)) {
                    base.Tables.Add(new uspDajBrojacDataTable(ds.Tables["uspDajBrojac"]));
                }
                if ((ds.Tables["vwArtikal"] != null)) {
                    base.Tables.Add(new vwArtikalDataTable(ds.Tables["vwArtikal"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablevwVezaArtikalDobavljac = ((vwVezaArtikalDobavljacDataTable)(base.Tables["vwVezaArtikalDobavljac"]));
            if ((initTable == true)) {
                if ((this.tablevwVezaArtikalDobavljac != null)) {
                    this.tablevwVezaArtikalDobavljac.InitVars();
                }
            }
            this.tableuspDajBrojac = ((uspDajBrojacDataTable)(base.Tables["uspDajBrojac"]));
            if ((initTable == true)) {
                if ((this.tableuspDajBrojac != null)) {
                    this.tableuspDajBrojac.InitVars();
                }
            }
            this.tablevwArtikal = ((vwArtikalDataTable)(base.Tables["vwArtikal"]));
            if ((initTable == true)) {
                if ((this.tablevwArtikal != null)) {
                    this.tablevwArtikal.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "ArtikalDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ArtikalDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablevwVezaArtikalDobavljac = new vwVezaArtikalDobavljacDataTable();
            base.Tables.Add(this.tablevwVezaArtikalDobavljac);
            this.tableuspDajBrojac = new uspDajBrojacDataTable();
            base.Tables.Add(this.tableuspDajBrojac);
            this.tablevwArtikal = new vwArtikalDataTable();
            base.Tables.Add(this.tablevwArtikal);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializevwVezaArtikalDobavljac() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeuspDajBrojac() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializevwArtikal() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ArtikalDataSet ds = new ArtikalDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void vwVezaArtikalDobavljacRowChangeEventHandler(object sender, vwVezaArtikalDobavljacRowChangeEvent e);
        
        public delegate void uspDajBrojacRowChangeEventHandler(object sender, uspDajBrojacRowChangeEvent e);
        
        public delegate void vwArtikalRowChangeEventHandler(object sender, vwArtikalRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class vwVezaArtikalDobavljacDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnArtikal_ID;
            
            private global::System.Data.DataColumn columnPoslovniPartner_ID;
            
            private global::System.Data.DataColumn columnDobavljač;
            
            private global::System.Data.DataColumn columnCena;
            
            private global::System.Data.DataColumn columnDatum_ažuriranja;
            
            private global::System.Data.DataColumn columnTelefon;
            
            private global::System.Data.DataColumn columnKontakt_osoba;
            
            private global::System.Data.DataColumn columnNapomena;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwVezaArtikalDobavljacDataTable() {
                this.TableName = "vwVezaArtikalDobavljac";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal vwVezaArtikalDobavljacDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected vwVezaArtikalDobavljacDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Artikal_IDColumn {
                get {
                    return this.columnArtikal_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PoslovniPartner_IDColumn {
                get {
                    return this.columnPoslovniPartner_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DobavljačColumn {
                get {
                    return this.columnDobavljač;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CenaColumn {
                get {
                    return this.columnCena;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Datum_ažuriranjaColumn {
                get {
                    return this.columnDatum_ažuriranja;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TelefonColumn {
                get {
                    return this.columnTelefon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Kontakt_osobaColumn {
                get {
                    return this.columnKontakt_osoba;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NapomenaColumn {
                get {
                    return this.columnNapomena;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwVezaArtikalDobavljacRow this[int index] {
                get {
                    return ((vwVezaArtikalDobavljacRow)(this.Rows[index]));
                }
            }
            
            public event vwVezaArtikalDobavljacRowChangeEventHandler vwVezaArtikalDobavljacRowChanging;
            
            public event vwVezaArtikalDobavljacRowChangeEventHandler vwVezaArtikalDobavljacRowChanged;
            
            public event vwVezaArtikalDobavljacRowChangeEventHandler vwVezaArtikalDobavljacRowDeleting;
            
            public event vwVezaArtikalDobavljacRowChangeEventHandler vwVezaArtikalDobavljacRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddvwVezaArtikalDobavljacRow(vwVezaArtikalDobavljacRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwVezaArtikalDobavljacRow AddvwVezaArtikalDobavljacRow(int Artikal_ID, short PoslovniPartner_ID, string Dobavljač, decimal Cena, System.DateTime Datum_ažuriranja, string Telefon, string Kontakt_osoba, string Napomena) {
                vwVezaArtikalDobavljacRow rowvwVezaArtikalDobavljacRow = ((vwVezaArtikalDobavljacRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Artikal_ID,
                        PoslovniPartner_ID,
                        Dobavljač,
                        Cena,
                        Datum_ažuriranja,
                        Telefon,
                        Kontakt_osoba,
                        Napomena};
                rowvwVezaArtikalDobavljacRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowvwVezaArtikalDobavljacRow);
                return rowvwVezaArtikalDobavljacRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                vwVezaArtikalDobavljacDataTable cln = ((vwVezaArtikalDobavljacDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new vwVezaArtikalDobavljacDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnArtikal_ID = base.Columns["Artikal_ID"];
                this.columnPoslovniPartner_ID = base.Columns["PoslovniPartner_ID"];
                this.columnDobavljač = base.Columns["Dobavljač"];
                this.columnCena = base.Columns["Cena"];
                this.columnDatum_ažuriranja = base.Columns["Datum ažuriranja"];
                this.columnTelefon = base.Columns["Telefon"];
                this.columnKontakt_osoba = base.Columns["Kontakt osoba"];
                this.columnNapomena = base.Columns["Napomena"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnArtikal_ID = new global::System.Data.DataColumn("Artikal_ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnArtikal_ID);
                this.columnPoslovniPartner_ID = new global::System.Data.DataColumn("PoslovniPartner_ID", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPoslovniPartner_ID);
                this.columnDobavljač = new global::System.Data.DataColumn("Dobavljač", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDobavljač);
                this.columnCena = new global::System.Data.DataColumn("Cena", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCena);
                this.columnDatum_ažuriranja = new global::System.Data.DataColumn("Datum ažuriranja", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDatum_ažuriranja);
                this.columnTelefon = new global::System.Data.DataColumn("Telefon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTelefon);
                this.columnKontakt_osoba = new global::System.Data.DataColumn("Kontakt osoba", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKontakt_osoba);
                this.columnNapomena = new global::System.Data.DataColumn("Napomena", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNapomena);
                this.columnArtikal_ID.AllowDBNull = false;
                this.columnPoslovniPartner_ID.AllowDBNull = false;
                this.columnDobavljač.AllowDBNull = false;
                this.columnDobavljač.MaxLength = 60;
                this.columnCena.AllowDBNull = false;
                this.columnTelefon.MaxLength = 50;
                this.columnKontakt_osoba.MaxLength = 50;
                this.columnNapomena.MaxLength = 200;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwVezaArtikalDobavljacRow NewvwVezaArtikalDobavljacRow() {
                return ((vwVezaArtikalDobavljacRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new vwVezaArtikalDobavljacRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(vwVezaArtikalDobavljacRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.vwVezaArtikalDobavljacRowChanged != null)) {
                    this.vwVezaArtikalDobavljacRowChanged(this, new vwVezaArtikalDobavljacRowChangeEvent(((vwVezaArtikalDobavljacRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.vwVezaArtikalDobavljacRowChanging != null)) {
                    this.vwVezaArtikalDobavljacRowChanging(this, new vwVezaArtikalDobavljacRowChangeEvent(((vwVezaArtikalDobavljacRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.vwVezaArtikalDobavljacRowDeleted != null)) {
                    this.vwVezaArtikalDobavljacRowDeleted(this, new vwVezaArtikalDobavljacRowChangeEvent(((vwVezaArtikalDobavljacRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.vwVezaArtikalDobavljacRowDeleting != null)) {
                    this.vwVezaArtikalDobavljacRowDeleting(this, new vwVezaArtikalDobavljacRowChangeEvent(((vwVezaArtikalDobavljacRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovevwVezaArtikalDobavljacRow(vwVezaArtikalDobavljacRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ArtikalDataSet ds = new ArtikalDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "vwVezaArtikalDobavljacDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class uspDajBrojacDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnProizvođač;
            
            private global::System.Data.DataColumn columnNaziv_proizvoda;
            
            private global::System.Data.DataColumn columnBroj_proizvođača;
            
            private global::System.Data.DataColumn columnBrojač;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspDajBrojacDataTable() {
                this.TableName = "uspDajBrojac";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal uspDajBrojacDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected uspDajBrojacDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ProizvođačColumn {
                get {
                    return this.columnProizvođač;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Naziv_proizvodaColumn {
                get {
                    return this.columnNaziv_proizvoda;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Broj_proizvođačaColumn {
                get {
                    return this.columnBroj_proizvođača;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BrojačColumn {
                get {
                    return this.columnBrojač;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspDajBrojacRow this[int index] {
                get {
                    return ((uspDajBrojacRow)(this.Rows[index]));
                }
            }
            
            public event uspDajBrojacRowChangeEventHandler uspDajBrojacRowChanging;
            
            public event uspDajBrojacRowChangeEventHandler uspDajBrojacRowChanged;
            
            public event uspDajBrojacRowChangeEventHandler uspDajBrojacRowDeleting;
            
            public event uspDajBrojacRowChangeEventHandler uspDajBrojacRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AdduspDajBrojacRow(uspDajBrojacRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspDajBrojacRow AdduspDajBrojacRow(string Proizvođač, string Naziv_proizvoda, string Broj_proizvođača, int Brojač) {
                uspDajBrojacRow rowuspDajBrojacRow = ((uspDajBrojacRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Proizvođač,
                        Naziv_proizvoda,
                        Broj_proizvođača,
                        Brojač};
                rowuspDajBrojacRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowuspDajBrojacRow);
                return rowuspDajBrojacRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                uspDajBrojacDataTable cln = ((uspDajBrojacDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new uspDajBrojacDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnProizvođač = base.Columns["Proizvođač"];
                this.columnNaziv_proizvoda = base.Columns["Naziv proizvoda"];
                this.columnBroj_proizvođača = base.Columns["Broj proizvođača"];
                this.columnBrojač = base.Columns["Brojač"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnProizvođač = new global::System.Data.DataColumn("Proizvođač", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProizvođač);
                this.columnNaziv_proizvoda = new global::System.Data.DataColumn("Naziv proizvoda", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNaziv_proizvoda);
                this.columnBroj_proizvođača = new global::System.Data.DataColumn("Broj proizvođača", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBroj_proizvođača);
                this.columnBrojač = new global::System.Data.DataColumn("Brojač", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBrojač);
                this.columnProizvođač.AllowDBNull = false;
                this.columnProizvođač.MaxLength = 60;
                this.columnBroj_proizvođača.AllowDBNull = false;
                this.columnBroj_proizvođača.MaxLength = 66;
                this.columnBrojač.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspDajBrojacRow NewuspDajBrojacRow() {
                return ((uspDajBrojacRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new uspDajBrojacRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(uspDajBrojacRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.uspDajBrojacRowChanged != null)) {
                    this.uspDajBrojacRowChanged(this, new uspDajBrojacRowChangeEvent(((uspDajBrojacRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.uspDajBrojacRowChanging != null)) {
                    this.uspDajBrojacRowChanging(this, new uspDajBrojacRowChangeEvent(((uspDajBrojacRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.uspDajBrojacRowDeleted != null)) {
                    this.uspDajBrojacRowDeleted(this, new uspDajBrojacRowChangeEvent(((uspDajBrojacRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.uspDajBrojacRowDeleting != null)) {
                    this.uspDajBrojacRowDeleting(this, new uspDajBrojacRowChangeEvent(((uspDajBrojacRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveuspDajBrojacRow(uspDajBrojacRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ArtikalDataSet ds = new ArtikalDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "uspDajBrojacDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class vwArtikalDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnArtikal_ID;
            
            private global::System.Data.DataColumn columnProizvođač;
            
            private global::System.Data.DataColumn columnBroj_proizvoda;
            
            private global::System.Data.DataColumn columnNaziv_proizvoda;
            
            private global::System.Data.DataColumn columnCena_ugradnje;
            
            private global::System.Data.DataColumn columnNorma_sati;
            
            private global::System.Data.DataColumn columnCena;
            
            private global::System.Data.DataColumn columnNajpovoljniji_dobavljač;
            
            private global::System.Data.DataColumn columnKorisnik_programa;
            
            private global::System.Data.DataColumn columnNapomena;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwArtikalDataTable() {
                this.TableName = "vwArtikal";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal vwArtikalDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected vwArtikalDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Artikal_IDColumn {
                get {
                    return this.columnArtikal_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ProizvođačColumn {
                get {
                    return this.columnProizvođač;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Broj_proizvodaColumn {
                get {
                    return this.columnBroj_proizvoda;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Naziv_proizvodaColumn {
                get {
                    return this.columnNaziv_proizvoda;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Cena_ugradnjeColumn {
                get {
                    return this.columnCena_ugradnje;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Norma_satiColumn {
                get {
                    return this.columnNorma_sati;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CenaColumn {
                get {
                    return this.columnCena;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Najpovoljniji_dobavljačColumn {
                get {
                    return this.columnNajpovoljniji_dobavljač;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Korisnik_programaColumn {
                get {
                    return this.columnKorisnik_programa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NapomenaColumn {
                get {
                    return this.columnNapomena;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwArtikalRow this[int index] {
                get {
                    return ((vwArtikalRow)(this.Rows[index]));
                }
            }
            
            public event vwArtikalRowChangeEventHandler vwArtikalRowChanging;
            
            public event vwArtikalRowChangeEventHandler vwArtikalRowChanged;
            
            public event vwArtikalRowChangeEventHandler vwArtikalRowDeleting;
            
            public event vwArtikalRowChangeEventHandler vwArtikalRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddvwArtikalRow(vwArtikalRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwArtikalRow AddvwArtikalRow(int Artikal_ID, string Proizvođač, string Broj_proizvoda, string Naziv_proizvoda, string Cena_ugradnje, string Norma_sati, decimal Cena, string Najpovoljniji_dobavljač, string Korisnik_programa, string Napomena) {
                vwArtikalRow rowvwArtikalRow = ((vwArtikalRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Artikal_ID,
                        Proizvođač,
                        Broj_proizvoda,
                        Naziv_proizvoda,
                        Cena_ugradnje,
                        Norma_sati,
                        Cena,
                        Najpovoljniji_dobavljač,
                        Korisnik_programa,
                        Napomena};
                rowvwArtikalRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowvwArtikalRow);
                return rowvwArtikalRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwArtikalRow FindByArtikal_ID(int Artikal_ID) {
                return ((vwArtikalRow)(this.Rows.Find(new object[] {
                            Artikal_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                vwArtikalDataTable cln = ((vwArtikalDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new vwArtikalDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnArtikal_ID = base.Columns["Artikal_ID"];
                this.columnProizvođač = base.Columns["Proizvođač"];
                this.columnBroj_proizvoda = base.Columns["Broj proizvoda"];
                this.columnNaziv_proizvoda = base.Columns["Naziv proizvoda"];
                this.columnCena_ugradnje = base.Columns["Cena ugradnje"];
                this.columnNorma_sati = base.Columns["Norma sati"];
                this.columnCena = base.Columns["Cena"];
                this.columnNajpovoljniji_dobavljač = base.Columns["Najpovoljniji dobavljač"];
                this.columnKorisnik_programa = base.Columns["Korisnik programa"];
                this.columnNapomena = base.Columns["Napomena"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnArtikal_ID = new global::System.Data.DataColumn("Artikal_ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnArtikal_ID);
                this.columnProizvođač = new global::System.Data.DataColumn("Proizvođač", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProizvođač);
                this.columnBroj_proizvoda = new global::System.Data.DataColumn("Broj proizvoda", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBroj_proizvoda);
                this.columnNaziv_proizvoda = new global::System.Data.DataColumn("Naziv proizvoda", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNaziv_proizvoda);
                this.columnCena_ugradnje = new global::System.Data.DataColumn("Cena ugradnje", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCena_ugradnje);
                this.columnNorma_sati = new global::System.Data.DataColumn("Norma sati", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNorma_sati);
                this.columnCena = new global::System.Data.DataColumn("Cena", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCena);
                this.columnNajpovoljniji_dobavljač = new global::System.Data.DataColumn("Najpovoljniji dobavljač", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNajpovoljniji_dobavljač);
                this.columnKorisnik_programa = new global::System.Data.DataColumn("Korisnik programa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKorisnik_programa);
                this.columnNapomena = new global::System.Data.DataColumn("Napomena", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNapomena);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnArtikal_ID}, true));
                this.columnArtikal_ID.AllowDBNull = false;
                this.columnArtikal_ID.Unique = true;
                this.columnProizvođač.AllowDBNull = false;
                this.columnProizvođač.MaxLength = 60;
                this.columnBroj_proizvoda.AllowDBNull = false;
                this.columnBroj_proizvoda.MaxLength = 66;
                this.columnNaziv_proizvoda.AllowDBNull = false;
                this.columnNaziv_proizvoda.MaxLength = 2147483647;
                this.columnCena.ReadOnly = true;
                this.columnNajpovoljniji_dobavljač.ReadOnly = true;
                this.columnNajpovoljniji_dobavljač.MaxLength = 60;
                this.columnKorisnik_programa.MaxLength = 60;
                this.columnNapomena.MaxLength = 200;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwArtikalRow NewvwArtikalRow() {
                return ((vwArtikalRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new vwArtikalRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(vwArtikalRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.vwArtikalRowChanged != null)) {
                    this.vwArtikalRowChanged(this, new vwArtikalRowChangeEvent(((vwArtikalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.vwArtikalRowChanging != null)) {
                    this.vwArtikalRowChanging(this, new vwArtikalRowChangeEvent(((vwArtikalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.vwArtikalRowDeleted != null)) {
                    this.vwArtikalRowDeleted(this, new vwArtikalRowChangeEvent(((vwArtikalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.vwArtikalRowDeleting != null)) {
                    this.vwArtikalRowDeleting(this, new vwArtikalRowChangeEvent(((vwArtikalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovevwArtikalRow(vwArtikalRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ArtikalDataSet ds = new ArtikalDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "vwArtikalDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class vwVezaArtikalDobavljacRow : global::System.Data.DataRow {
            
            private vwVezaArtikalDobavljacDataTable tablevwVezaArtikalDobavljac;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal vwVezaArtikalDobavljacRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablevwVezaArtikalDobavljac = ((vwVezaArtikalDobavljacDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Artikal_ID {
                get {
                    return ((int)(this[this.tablevwVezaArtikalDobavljac.Artikal_IDColumn]));
                }
                set {
                    this[this.tablevwVezaArtikalDobavljac.Artikal_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short PoslovniPartner_ID {
                get {
                    return ((short)(this[this.tablevwVezaArtikalDobavljac.PoslovniPartner_IDColumn]));
                }
                set {
                    this[this.tablevwVezaArtikalDobavljac.PoslovniPartner_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Dobavljač {
                get {
                    return ((string)(this[this.tablevwVezaArtikalDobavljac.DobavljačColumn]));
                }
                set {
                    this[this.tablevwVezaArtikalDobavljac.DobavljačColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Cena {
                get {
                    return ((decimal)(this[this.tablevwVezaArtikalDobavljac.CenaColumn]));
                }
                set {
                    this[this.tablevwVezaArtikalDobavljac.CenaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime Datum_ažuriranja {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablevwVezaArtikalDobavljac.Datum_ažuriranjaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Datum ažuriranja\' in table \'vwVezaArtikalDobavljac\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tablevwVezaArtikalDobavljac.Datum_ažuriranjaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Telefon {
                get {
                    try {
                        return ((string)(this[this.tablevwVezaArtikalDobavljac.TelefonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Telefon\' in table \'vwVezaArtikalDobavljac\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwVezaArtikalDobavljac.TelefonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Kontakt_osoba {
                get {
                    try {
                        return ((string)(this[this.tablevwVezaArtikalDobavljac.Kontakt_osobaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Kontakt osoba\' in table \'vwVezaArtikalDobavljac\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tablevwVezaArtikalDobavljac.Kontakt_osobaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Napomena {
                get {
                    try {
                        return ((string)(this[this.tablevwVezaArtikalDobavljac.NapomenaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Napomena\' in table \'vwVezaArtikalDobavljac\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwVezaArtikalDobavljac.NapomenaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDatum_ažuriranjaNull() {
                return this.IsNull(this.tablevwVezaArtikalDobavljac.Datum_ažuriranjaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDatum_ažuriranjaNull() {
                this[this.tablevwVezaArtikalDobavljac.Datum_ažuriranjaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTelefonNull() {
                return this.IsNull(this.tablevwVezaArtikalDobavljac.TelefonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTelefonNull() {
                this[this.tablevwVezaArtikalDobavljac.TelefonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKontakt_osobaNull() {
                return this.IsNull(this.tablevwVezaArtikalDobavljac.Kontakt_osobaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKontakt_osobaNull() {
                this[this.tablevwVezaArtikalDobavljac.Kontakt_osobaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNapomenaNull() {
                return this.IsNull(this.tablevwVezaArtikalDobavljac.NapomenaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNapomenaNull() {
                this[this.tablevwVezaArtikalDobavljac.NapomenaColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class uspDajBrojacRow : global::System.Data.DataRow {
            
            private uspDajBrojacDataTable tableuspDajBrojac;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal uspDajBrojacRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableuspDajBrojac = ((uspDajBrojacDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Proizvođač {
                get {
                    return ((string)(this[this.tableuspDajBrojac.ProizvođačColumn]));
                }
                set {
                    this[this.tableuspDajBrojac.ProizvođačColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Naziv_proizvoda {
                get {
                    try {
                        return ((string)(this[this.tableuspDajBrojac.Naziv_proizvodaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Naziv proizvoda\' in table \'uspDajBrojac\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspDajBrojac.Naziv_proizvodaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Broj_proizvođača {
                get {
                    return ((string)(this[this.tableuspDajBrojac.Broj_proizvođačaColumn]));
                }
                set {
                    this[this.tableuspDajBrojac.Broj_proizvođačaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Brojač {
                get {
                    return ((int)(this[this.tableuspDajBrojac.BrojačColumn]));
                }
                set {
                    this[this.tableuspDajBrojac.BrojačColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNaziv_proizvodaNull() {
                return this.IsNull(this.tableuspDajBrojac.Naziv_proizvodaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNaziv_proizvodaNull() {
                this[this.tableuspDajBrojac.Naziv_proizvodaColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class vwArtikalRow : global::System.Data.DataRow {
            
            private vwArtikalDataTable tablevwArtikal;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal vwArtikalRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablevwArtikal = ((vwArtikalDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Artikal_ID {
                get {
                    return ((int)(this[this.tablevwArtikal.Artikal_IDColumn]));
                }
                set {
                    this[this.tablevwArtikal.Artikal_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Proizvođač {
                get {
                    return ((string)(this[this.tablevwArtikal.ProizvođačColumn]));
                }
                set {
                    this[this.tablevwArtikal.ProizvođačColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Broj_proizvoda {
                get {
                    return ((string)(this[this.tablevwArtikal.Broj_proizvodaColumn]));
                }
                set {
                    this[this.tablevwArtikal.Broj_proizvodaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Naziv_proizvoda {
                get {
                    return ((string)(this[this.tablevwArtikal.Naziv_proizvodaColumn]));
                }
                set {
                    this[this.tablevwArtikal.Naziv_proizvodaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Cena_ugradnje {
                get {
                    try {
                        return ((string)(this[this.tablevwArtikal.Cena_ugradnjeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Cena ugradnje\' in table \'vwArtikal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwArtikal.Cena_ugradnjeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Norma_sati {
                get {
                    try {
                        return ((string)(this[this.tablevwArtikal.Norma_satiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Norma sati\' in table \'vwArtikal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwArtikal.Norma_satiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal Cena {
                get {
                    try {
                        return ((decimal)(this[this.tablevwArtikal.CenaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Cena\' in table \'vwArtikal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwArtikal.CenaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Najpovoljniji_dobavljač {
                get {
                    try {
                        return ((string)(this[this.tablevwArtikal.Najpovoljniji_dobavljačColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Najpovoljniji dobavljač\' in table \'vwArtikal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwArtikal.Najpovoljniji_dobavljačColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Korisnik_programa {
                get {
                    try {
                        return ((string)(this[this.tablevwArtikal.Korisnik_programaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Korisnik programa\' in table \'vwArtikal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwArtikal.Korisnik_programaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Napomena {
                get {
                    try {
                        return ((string)(this[this.tablevwArtikal.NapomenaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Napomena\' in table \'vwArtikal\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwArtikal.NapomenaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCena_ugradnjeNull() {
                return this.IsNull(this.tablevwArtikal.Cena_ugradnjeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCena_ugradnjeNull() {
                this[this.tablevwArtikal.Cena_ugradnjeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNorma_satiNull() {
                return this.IsNull(this.tablevwArtikal.Norma_satiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNorma_satiNull() {
                this[this.tablevwArtikal.Norma_satiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCenaNull() {
                return this.IsNull(this.tablevwArtikal.CenaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCenaNull() {
                this[this.tablevwArtikal.CenaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNajpovoljniji_dobavljačNull() {
                return this.IsNull(this.tablevwArtikal.Najpovoljniji_dobavljačColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNajpovoljniji_dobavljačNull() {
                this[this.tablevwArtikal.Najpovoljniji_dobavljačColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKorisnik_programaNull() {
                return this.IsNull(this.tablevwArtikal.Korisnik_programaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKorisnik_programaNull() {
                this[this.tablevwArtikal.Korisnik_programaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNapomenaNull() {
                return this.IsNull(this.tablevwArtikal.NapomenaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNapomenaNull() {
                this[this.tablevwArtikal.NapomenaColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class vwVezaArtikalDobavljacRowChangeEvent : global::System.EventArgs {
            
            private vwVezaArtikalDobavljacRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwVezaArtikalDobavljacRowChangeEvent(vwVezaArtikalDobavljacRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwVezaArtikalDobavljacRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class uspDajBrojacRowChangeEvent : global::System.EventArgs {
            
            private uspDajBrojacRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspDajBrojacRowChangeEvent(uspDajBrojacRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspDajBrojacRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class vwArtikalRowChangeEvent : global::System.EventArgs {
            
            private vwArtikalRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwArtikalRowChangeEvent(vwArtikalRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwArtikalRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591