//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace LAV.DS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("StampajPodatkeOKorisnikuDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class StampajPodatkeOKorisnikuDataSet : global::System.Data.DataSet {
        
        private vwKorisnikProgramaDataTable tablevwKorisnikPrograma;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public StampajPodatkeOKorisnikuDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected StampajPodatkeOKorisnikuDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["vwKorisnikPrograma"] != null)) {
                    base.Tables.Add(new vwKorisnikProgramaDataTable(ds.Tables["vwKorisnikPrograma"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public vwKorisnikProgramaDataTable vwKorisnikPrograma {
            get {
                return this.tablevwKorisnikPrograma;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            StampajPodatkeOKorisnikuDataSet cln = ((StampajPodatkeOKorisnikuDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["vwKorisnikPrograma"] != null)) {
                    base.Tables.Add(new vwKorisnikProgramaDataTable(ds.Tables["vwKorisnikPrograma"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablevwKorisnikPrograma = ((vwKorisnikProgramaDataTable)(base.Tables["vwKorisnikPrograma"]));
            if ((initTable == true)) {
                if ((this.tablevwKorisnikPrograma != null)) {
                    this.tablevwKorisnikPrograma.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "StampajPodatkeOKorisnikuDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/StampajPodatkeOKorisnikuDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablevwKorisnikPrograma = new vwKorisnikProgramaDataTable();
            base.Tables.Add(this.tablevwKorisnikPrograma);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializevwKorisnikPrograma() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            StampajPodatkeOKorisnikuDataSet ds = new StampajPodatkeOKorisnikuDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void vwKorisnikProgramaRowChangeEventHandler(object sender, vwKorisnikProgramaRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class vwKorisnikProgramaDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnKorisnikPrograma_ID;
            
            private global::System.Data.DataColumn columnNaziv;
            
            private global::System.Data.DataColumn columnMesto_ID;
            
            private global::System.Data.DataColumn columnMesto;
            
            private global::System.Data.DataColumn columnPozivni_broj;
            
            private global::System.Data.DataColumn columnPoštanski_broj;
            
            private global::System.Data.DataColumn columnAdresa;
            
            private global::System.Data.DataColumn columnPIB;
            
            private global::System.Data.DataColumn columnŽiro_račun;
            
            private global::System.Data.DataColumn columnTelefon;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwKorisnikProgramaDataTable() {
                this.TableName = "vwKorisnikPrograma";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal vwKorisnikProgramaDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected vwKorisnikProgramaDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KorisnikPrograma_IDColumn {
                get {
                    return this.columnKorisnikPrograma_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NazivColumn {
                get {
                    return this.columnNaziv;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Mesto_IDColumn {
                get {
                    return this.columnMesto_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MestoColumn {
                get {
                    return this.columnMesto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Pozivni_brojColumn {
                get {
                    return this.columnPozivni_broj;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Poštanski_brojColumn {
                get {
                    return this.columnPoštanski_broj;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AdresaColumn {
                get {
                    return this.columnAdresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PIBColumn {
                get {
                    return this.columnPIB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Žiro_računColumn {
                get {
                    return this.columnŽiro_račun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TelefonColumn {
                get {
                    return this.columnTelefon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwKorisnikProgramaRow this[int index] {
                get {
                    return ((vwKorisnikProgramaRow)(this.Rows[index]));
                }
            }
            
            public event vwKorisnikProgramaRowChangeEventHandler vwKorisnikProgramaRowChanging;
            
            public event vwKorisnikProgramaRowChangeEventHandler vwKorisnikProgramaRowChanged;
            
            public event vwKorisnikProgramaRowChangeEventHandler vwKorisnikProgramaRowDeleting;
            
            public event vwKorisnikProgramaRowChangeEventHandler vwKorisnikProgramaRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddvwKorisnikProgramaRow(vwKorisnikProgramaRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwKorisnikProgramaRow AddvwKorisnikProgramaRow(byte KorisnikPrograma_ID, string Naziv, byte Mesto_ID, string Mesto, string Pozivni_broj, string Poštanski_broj, string Adresa, string PIB, string Žiro_račun, string Telefon) {
                vwKorisnikProgramaRow rowvwKorisnikProgramaRow = ((vwKorisnikProgramaRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        KorisnikPrograma_ID,
                        Naziv,
                        Mesto_ID,
                        Mesto,
                        Pozivni_broj,
                        Poštanski_broj,
                        Adresa,
                        PIB,
                        Žiro_račun,
                        Telefon};
                rowvwKorisnikProgramaRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowvwKorisnikProgramaRow);
                return rowvwKorisnikProgramaRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwKorisnikProgramaRow FindByKorisnikPrograma_ID(byte KorisnikPrograma_ID) {
                return ((vwKorisnikProgramaRow)(this.Rows.Find(new object[] {
                            KorisnikPrograma_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                vwKorisnikProgramaDataTable cln = ((vwKorisnikProgramaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new vwKorisnikProgramaDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnKorisnikPrograma_ID = base.Columns["KorisnikPrograma_ID"];
                this.columnNaziv = base.Columns["Naziv"];
                this.columnMesto_ID = base.Columns["Mesto_ID"];
                this.columnMesto = base.Columns["Mesto"];
                this.columnPozivni_broj = base.Columns["Pozivni broj"];
                this.columnPoštanski_broj = base.Columns["Poštanski broj"];
                this.columnAdresa = base.Columns["Adresa"];
                this.columnPIB = base.Columns["PIB"];
                this.columnŽiro_račun = base.Columns["Žiro račun"];
                this.columnTelefon = base.Columns["Telefon"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnKorisnikPrograma_ID = new global::System.Data.DataColumn("KorisnikPrograma_ID", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKorisnikPrograma_ID);
                this.columnNaziv = new global::System.Data.DataColumn("Naziv", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNaziv);
                this.columnMesto_ID = new global::System.Data.DataColumn("Mesto_ID", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMesto_ID);
                this.columnMesto = new global::System.Data.DataColumn("Mesto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMesto);
                this.columnPozivni_broj = new global::System.Data.DataColumn("Pozivni broj", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPozivni_broj);
                this.columnPoštanski_broj = new global::System.Data.DataColumn("Poštanski broj", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPoštanski_broj);
                this.columnAdresa = new global::System.Data.DataColumn("Adresa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAdresa);
                this.columnPIB = new global::System.Data.DataColumn("PIB", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPIB);
                this.columnŽiro_račun = new global::System.Data.DataColumn("Žiro račun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnŽiro_račun);
                this.columnTelefon = new global::System.Data.DataColumn("Telefon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTelefon);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnKorisnikPrograma_ID}, true));
                this.columnKorisnikPrograma_ID.AllowDBNull = false;
                this.columnKorisnikPrograma_ID.Unique = true;
                this.columnNaziv.AllowDBNull = false;
                this.columnNaziv.MaxLength = 60;
                this.columnMesto_ID.AllowDBNull = false;
                this.columnMesto.AllowDBNull = false;
                this.columnMesto.MaxLength = 30;
                this.columnPozivni_broj.MaxLength = 5;
                this.columnPoštanski_broj.MaxLength = 5;
                this.columnAdresa.AllowDBNull = false;
                this.columnAdresa.MaxLength = 50;
                this.columnPIB.AllowDBNull = false;
                this.columnPIB.MaxLength = 15;
                this.columnŽiro_račun.AllowDBNull = false;
                this.columnŽiro_račun.MaxLength = 50;
                this.columnTelefon.AllowDBNull = false;
                this.columnTelefon.MaxLength = 50;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwKorisnikProgramaRow NewvwKorisnikProgramaRow() {
                return ((vwKorisnikProgramaRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new vwKorisnikProgramaRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(vwKorisnikProgramaRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.vwKorisnikProgramaRowChanged != null)) {
                    this.vwKorisnikProgramaRowChanged(this, new vwKorisnikProgramaRowChangeEvent(((vwKorisnikProgramaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.vwKorisnikProgramaRowChanging != null)) {
                    this.vwKorisnikProgramaRowChanging(this, new vwKorisnikProgramaRowChangeEvent(((vwKorisnikProgramaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.vwKorisnikProgramaRowDeleted != null)) {
                    this.vwKorisnikProgramaRowDeleted(this, new vwKorisnikProgramaRowChangeEvent(((vwKorisnikProgramaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.vwKorisnikProgramaRowDeleting != null)) {
                    this.vwKorisnikProgramaRowDeleting(this, new vwKorisnikProgramaRowChangeEvent(((vwKorisnikProgramaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovevwKorisnikProgramaRow(vwKorisnikProgramaRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                StampajPodatkeOKorisnikuDataSet ds = new StampajPodatkeOKorisnikuDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "vwKorisnikProgramaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class vwKorisnikProgramaRow : global::System.Data.DataRow {
            
            private vwKorisnikProgramaDataTable tablevwKorisnikPrograma;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal vwKorisnikProgramaRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablevwKorisnikPrograma = ((vwKorisnikProgramaDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte KorisnikPrograma_ID {
                get {
                    return ((byte)(this[this.tablevwKorisnikPrograma.KorisnikPrograma_IDColumn]));
                }
                set {
                    this[this.tablevwKorisnikPrograma.KorisnikPrograma_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Naziv {
                get {
                    return ((string)(this[this.tablevwKorisnikPrograma.NazivColumn]));
                }
                set {
                    this[this.tablevwKorisnikPrograma.NazivColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Mesto_ID {
                get {
                    return ((byte)(this[this.tablevwKorisnikPrograma.Mesto_IDColumn]));
                }
                set {
                    this[this.tablevwKorisnikPrograma.Mesto_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Mesto {
                get {
                    return ((string)(this[this.tablevwKorisnikPrograma.MestoColumn]));
                }
                set {
                    this[this.tablevwKorisnikPrograma.MestoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Pozivni_broj {
                get {
                    try {
                        return ((string)(this[this.tablevwKorisnikPrograma.Pozivni_brojColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Pozivni broj\' in table \'vwKorisnikPrograma\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwKorisnikPrograma.Pozivni_brojColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Poštanski_broj {
                get {
                    try {
                        return ((string)(this[this.tablevwKorisnikPrograma.Poštanski_brojColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Poštanski broj\' in table \'vwKorisnikPrograma\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablevwKorisnikPrograma.Poštanski_brojColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Adresa {
                get {
                    return ((string)(this[this.tablevwKorisnikPrograma.AdresaColumn]));
                }
                set {
                    this[this.tablevwKorisnikPrograma.AdresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PIB {
                get {
                    return ((string)(this[this.tablevwKorisnikPrograma.PIBColumn]));
                }
                set {
                    this[this.tablevwKorisnikPrograma.PIBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Žiro_račun {
                get {
                    return ((string)(this[this.tablevwKorisnikPrograma.Žiro_računColumn]));
                }
                set {
                    this[this.tablevwKorisnikPrograma.Žiro_računColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Telefon {
                get {
                    return ((string)(this[this.tablevwKorisnikPrograma.TelefonColumn]));
                }
                set {
                    this[this.tablevwKorisnikPrograma.TelefonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPozivni_brojNull() {
                return this.IsNull(this.tablevwKorisnikPrograma.Pozivni_brojColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPozivni_brojNull() {
                this[this.tablevwKorisnikPrograma.Pozivni_brojColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPoštanski_brojNull() {
                return this.IsNull(this.tablevwKorisnikPrograma.Poštanski_brojColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPoštanski_brojNull() {
                this[this.tablevwKorisnikPrograma.Poštanski_brojColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class vwKorisnikProgramaRowChangeEvent : global::System.EventArgs {
            
            private vwKorisnikProgramaRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwKorisnikProgramaRowChangeEvent(vwKorisnikProgramaRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public vwKorisnikProgramaRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591