/*    This SQL DDL script was generated by Microsoft Visual Studio (Release Date: LOCAL BUILD). */

/*    Driver Used : Microsoft Visual Studio - Microsoft SQL Server Driver.                    */
/*    Document    : C:\DOCUMENTS AND SETTINGS\OLIVER\DESKTOP\ORM\TD_ER.VSD.                   */
/*    Time Created: 9. July 2009 18:22.                                                       */
/*    Operation   : From Visio Generate Wizard.                                               */
/*    Connected data source : No connection.                                                  */
/*    Connected server      : No connection.                                                  */
/*    Connected database    : Not applicable.                                                 */



SET QUOTED_IDENTIFIER ON

go


/* Create TD database.                                                                        */
use master  

go

CREATE DATABASE [Lav_Pocetna] ON  PRIMARY 
( NAME = N'Lav', FILENAME = N'D:\LavAuto\SQL_Baze\Lav_Pocetna\Lav.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Lav_log', FILENAME = N'D:\LavAuto\SQL_Baze\Lav_Pocetna\Lav_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

go

use [Lav_Pocetna]

--go

/* Create new table "VezaUgradnjaKriterijum".                                                 */
/* "VezaUgradnjaKriterijum" : Table of VezaUgradnjaKriterijum                                 */
/* 	"VezaUgradnjaKriterijum_ID" : VezaUgradnjaKriterijumID identifies VezaUgradnjaKriterijum  */
/* 	"UgradnjaArtikal_ID" : VezaUgradnjaKriterijum ima Ugradnja                                */
/* 		Role one (Artikal) of fact: {Artikal} se ugradjuje u TipAutomobila.                      */
/* 		Role two (ArtikalID) of fact: Artikal is identified by {ArtikalID}.                      */
/* 	"UgradnjaTipAutomobila_ID" : VezaUgradnjaKriterijum ima Ugradnja                          */
/* 		Role two (TipAutomobila) of fact: Artikal se ugradjuje u {TipAutomobila}.                */
/* 		Role two (TipAutomobilaID) of fact: TipAutomobila is identified by {TipAutomobilaID}.    */
/* 	"Kriterijum_ID" : VezaUgradnjaKriterijum ima Kriterijum                                   */
/* 	"Vrednost" : VezaUgradnjaKriterijum vrednost uslova je nvarchar(60)                       */
/* 	"Opis_ID" : VezaUgradnjaKriterijum opis uslova je Opis                                    */  
create table "VezaUgradnjaKriterijum" ( 
	"VezaUgradnjaKriterijum_ID" int identity not null,
	"UgradnjaArtikal_ID" int not null,
	"UgradnjaTipAutomobila_ID" int not null,
	"Kriterijum_ID" smallint not null,
	"Vrednost" nvarchar(60) null,
	"Opis_ID" int null)  

go

/* Create table level checks for table VezaUgradnjaKriterijum.                                */
alter table "VezaUgradnjaKriterijum" add constraint VezaUgradnjaKriterijum_excl check ( ("Vrednost" is null) or
                ("Opis_ID" is null) ) 

go

alter table "VezaUgradnjaKriterijum"
	add constraint "VezaUgradnjaKriterijum_PK" primary key ("VezaUgradnjaKriterijum_ID")   


go

/* Create new table "VezaArtikalKriterijum".                                                  */
/* "VezaArtikalKriterijum" : Table of VezaArtikalKriterijum                                   */
/* 	"VezaArtikalKriterijum_ID" : VezaArtikalKriterijumID identifies VezaArtikalKriterijum     */
/* 	"Artikal_ID" : VezaArtikalKriterijum ima Artikal                                          */
/* 	"Kriterijum_ID" : VezaArtikalKriterijum ima Kriterijum                                    */
/* 	"Vrednost" : VezaArtikalKriterijum vrednost je nvarchar(60)                               */
/* 	"Opis_ID" : VezaArtikalKriterijum ima Opis                                                */  
create table "VezaArtikalKriterijum" ( 
	"VezaArtikalKriterijum_ID" int identity not null,
	"Artikal_ID" int not null,
	"Kriterijum_ID" smallint not null,
	"Vrednost" nvarchar(60) null,
	"Opis_ID" int null)  

go

/* Create table level checks for table VezaArtikalKriterijum.                                 */
alter table "VezaArtikalKriterijum" add constraint VezaArtikalKriterijum_excl check ( ("Vrednost" is null) or
                ("Opis_ID" is null) ) 

go

alter table "VezaArtikalKriterijum"
	add constraint "VezaArtikalKriterijum_PK" primary key ("VezaArtikalKriterijum_ID")   


go

/* Create new table "Ugradnja".                                                               */
/* "Ugradnja" : Table of Ugradnja                                                             */
/* 	"Artikal_ID" : Artikal se ugradjuje u TipAutomobila                                       */
/* 		Role one (Artikal) of fact: {Artikal} se ugradjuje u TipAutomobila.                      */
/* 		Role two (ArtikalID) of fact: Artikal is identified by {ArtikalID}.                      */
/* 	"TipAutomobila_ID" : Artikal se ugradjuje u TipAutomobila                                 */
/* 		Role two (TipAutomobila) of fact: Artikal se ugradjuje u {TipAutomobila}.                */
/* 		Role two (TipAutomobilaID) of fact: TipAutomobila is identified by {TipAutomobilaID}.    */  
create table "Ugradnja" ( 
	"Artikal_ID" int not null,
	"TipAutomobila_ID" int not null)  

go

alter table "Ugradnja"
	add constraint "Ugradnja_PK" primary key ("Artikal_ID", "TipAutomobila_ID")   


go

/* Create new table "VezaArtikalBrojZaPretragu".                                              */
/* "VezaArtikalBrojZaPretragu" : Table of VezaArtikalBrojZaPretragu                           */
/* 	"VezaArtikalBrojZaPretragu_ID" : VezaArtikalBrojZaPretraguID identifies VezaArtikalBrojZaPretragu */
/* 	"Artikal_ID" : VezaArtikalBrojZaPretragu ima Artikal                                      */
/* 	"BrojZaPretragu" : VezaArtikalBrojZaPretragu broj za pretragu je Varchar(100)             */
/* 	"BrojZaPrikazivanje" : VezaArtikalBrojZaPretragu broj za prikazivanje je Varchar(100)     */
/* 	"VrstaBrojaZaPretragu_ID" : VezaArtikalBrojZaPretragu ima VrstaBrojaZaPretragu            */
/* 	"Proizvodjac_ID" : VezaArtikalBrojZaPretragu ima Proizvodjac                              */  
create table "VezaArtikalBrojZaPretragu" ( 
	"VezaArtikalBrojZaPretragu_ID" int identity not null,
	"Artikal_ID" int not null,
	"BrojZaPretragu" varchar(100) not null,
	"BrojZaPrikazivanje" varchar(100) not null,
	"VrstaBrojaZaPretragu_ID" tinyint not null,
	"Proizvodjac_ID" smallint null)  

go

alter table "VezaArtikalBrojZaPretragu"
	add constraint "VezaArtikalBrojZaPretragu_PK" primary key ("VezaArtikalBrojZaPretragu_ID")   


go

/* Create new table "VezaArtikalStablo".                                                      */
/* "VezaArtikalStablo" : Artikal pripada Stablo                                               */
/* 	"Artikal_ID" : Artikal pripada Stablo                                                     */
/* 	"Stablo_ID" : Artikal pripada Stablo                                                      */  
create table "VezaArtikalStablo" ( 
	"Artikal_ID" int not null,
	"Stablo_ID" int not null)  

go

alter table "VezaArtikalStablo"
	add constraint "VezaArtikalStablo_PK" primary key ("Artikal_ID", "Stablo_ID")   


go

/* Create new table "VrstaBrojaZaPretragu".                                                   */
/* "VrstaBrojaZaPretragu" : Table of VrstaBrojaZaPretragu                                     */
/* 	"VrstaBrojaZaPretragu_ID" : VrstaBrojaZaPretraguID identifies VrstaBrojaZaPretragu        */
/* 	"Naziv" : VrstaBrojaZaPretragu ima varchar(30)                                            */  
create table "VrstaBrojaZaPretragu" ( 
	"VrstaBrojaZaPretragu_ID" tinyint not null,
	"Naziv" varchar(30) not null)  

go

alter table "VrstaBrojaZaPretragu"
	add constraint "VrstaBrojaZaPretragu_PK" primary key ("VrstaBrojaZaPretragu_ID")   


go

/* Create new table "Opis".                                                                   */
/* "Opis" : Table of Opis                                                                     */
/* 	"Opis_ID" : OpisID identifies Opis                                                        */
/* 	"Opis" : Opis tekst opisa je nvarchar(max)                                                */  
create table "Opis" ( 
	"Opis_ID" int not null,
	"Opis" nvarchar(max) not null)  

go

alter table "Opis"
	add constraint "Opis_PK" primary key ("Opis_ID")   


go

/* Create new table "TipAutomobila".                                                          */
/* "TipAutomobila" : Table of TipAutomobila                                                   */
/* 	"TipAutomobila_ID" : TipAutomobilaID identifies TipAutomobila                             */
/* 	"Opis_ID" : TipAutomobila ima Opis                                                        */
/* 	"ModelAutomobila_ID" : TipAutomobila je deo ModelAutomobila                               */
/* 	"ProizvodnjaOd" : TipAutomobila pocela proizvodnja int                                    */
/* 	"ProizvodnjaDo" : TipAutomobila kraj proizvodnje int                                      */
/* 	"SnagaKWOd" : TipAutomobila kw od smallint                                                */
/* 	"SnagaKWDo" : TipAutomobila kw do smallint                                                */
/* 	"SnagaKSOd" : TipAutomobila ks od smallint                                                */
/* 	"SnagaKSDo" : TipAutomobila ks do smallint                                                */
/* 	"ZapreminaCcm" : TipAutomobila ccm int                                                    */
/* 	"Cilindara" : TipAutomobila cilindara tinyint                                             */
/* 	"VentilaPoCilindru" : TipAutomobila ventila po cilindru tinyint                           */
/* 	"VrstaMotora_Opis" : TipAutomobila vrsta motora Opis                                      */
/* 	"VrstaGoriva_Opis" : TipAutomobila vrsta goriva Opis                                      */
/* 	"PripremaGoriva_Opis" : TipAutomobila priprema goriva Opis                                */
/* 	"VrstaKatalizatora_Opis" : TipAutomobila vrsta katalizatora Opis                          */
/* 	"NaponAkumulatora_Opis" : TipAutomobila voltaza akumulatora Opis                          */
/* 	"VrstaKaroserije_Opis" : TipAutomobila vrsta karoserije Opis                              */
/* 	"Vrata" : TipAutomobila vrata tinyint                                                     */
/* 	"RezervoarLitara" : TipAutomobila rezervoar litara tinyint                                */
/* 	"ABS_Opis" : TipAutomobila abs Opis                                                       */
/* 	"ASR_Opis" : TipAutomobila asr Opis                                                       */
/* 	"KocioniSistem_Opis" : TipAutomobila kocioni sistem Opis                                  */
/* 	"VrstaKocnica_Opis" : TipAutomobila vrsta kocnica Opis                                    */
/* 	"VrstaPogona_Opis" : TipAutomobila vrsta pogona Opis                                      */
/* 	"Menjac_Opis" : TipAutomobila menjac Opis                                                 */  
create table "TipAutomobila" ( 
	"TipAutomobila_ID" int not null,
	"Opis_ID" int not null,
	"ModelAutomobila_ID" int not null,
	"ProizvodnjaOd" int null,
	"ProizvodnjaDo" int null,
	"SnagaKWOd" smallint null,
	"SnagaKWDo" smallint null,
	"SnagaKSOd" smallint null,
	"SnagaKSDo" smallint null,
	"ZapreminaCcm" int null,
	"Cilindara" tinyint null,
	"VentilaPoCilindru" tinyint null,
	"VrstaMotora_Opis" int null,
	"VrstaGoriva_Opis" int null,
	"PripremaGoriva_Opis" int null,
	"VrstaKatalizatora_Opis" int null,
	"NaponAkumulatora_Opis" int null,
	"VrstaKaroserije_Opis" int null,
	"Vrata" tinyint null,
	"RezervoarLitara" tinyint null,
	"ABS_Opis" int null,
	"ASR_Opis" int null,
	"KocioniSistem_Opis" int null,
	"VrstaKocnica_Opis" int null,
	"VrstaPogona_Opis" int null,
	"Menjac_Opis" int null) ON 'PRIMARY'  

go

alter table "TipAutomobila"
	add constraint "TipAutomobila_PK" primary key clustered ("TipAutomobila_ID")   


go

/* Create new table "ModelAutomobila".                                                        */
/* "ModelAutomobila" : Table of ModelAutomobila                                               */
/* 	"ModelAutomobila_ID" : ModelAutomobilaID identifies ModelAutomobila                       */
/* 	"Opis_ID" : ModelAutomobila ima Opis                                                      */
/* 	"Proizvodjac_ID" : ModelAutomobila proizvodi Proizvodjac                                  */
/* 	"ProizvodnjaOd" : ModelAutomobila pocela proizvodnja int                                  */
/* 	"ProizvodnjaDo" : ModelAutomobila zavrsena proizvodnja int                                */  
create table "ModelAutomobila" ( 
	"ModelAutomobila_ID" int not null,
	"Opis_ID" int not null,
	"Proizvodjac_ID" smallint not null,
	"ProizvodnjaOd" int null,
	"ProizvodnjaDo" int null) ON 'PRIMARY'  

go

alter table "ModelAutomobila"
	add constraint "ModelAutomobila_PK" primary key clustered ("ModelAutomobila_ID")   


go

/* Create new table "VezaTipAutomobilaMotor".                                                 */
/* "VezaTipAutomobilaMotor" : Table of VezaTipAutomobilaMotor                                 */
/* 	"TipAutomobila_ID" : TipAutomobila ima Motor                                              */
/* 		Role one (TipAutomobila) of fact: {TipAutomobila} ima Motor.                             */
/* 		Role two (TipAutomobilaID) of fact: TipAutomobila is identified by {TipAutomobilaID}.    */
/* 	"Motor_ID" : TipAutomobila ima Motor                                                      */
/* 		Role two (Motor) of fact: TipAutomobila ima {Motor}.                                     */
/* 		Role two (MotorID) of fact: Motor is identified by {MotorID}.                            */
/* 	"UgradnjaOd" : VezaTipAutomobilaMotor pocetak ugradnje int                                */
/* 	"UgradnjaDo" : VezaTipAutomobilaMotor kraj  ugradnje int                                  */  
create table "VezaTipAutomobilaMotor" ( 
	"TipAutomobila_ID" int not null,
	"Motor_ID" smallint not null,
	"UgradnjaOd" int null,
	"UgradnjaDo" int null) ON 'PRIMARY'  

go

alter table "VezaTipAutomobilaMotor"
	add constraint "VezaTipAutomobilaMotor_PK" primary key clustered ("TipAutomobila_ID", "Motor_ID")   


go

/* Create new table "TipCvora".                                                               */
/* "TipCvora" : Table of TipCvora                                                             */
/* 	"TipCvora_ID" : TipCvoraID identifies TipCvora                                            */
/* 	"Naziv" : TipCvora ima varchar(20)                                                        */  
create table "TipCvora" ( 
	"TipCvora_ID" tinyint not null,
	"Naziv" varchar(20) not null) ON 'PRIMARY'  

go

alter table "TipCvora"
	add constraint "TipCvora_PK" primary key clustered ("TipCvora_ID")   


go

/* Create new table "Stablo".                                                                 */
/* "Stablo" : Table of Stablo                                                                 */
/* 	"Stablo_ID" : StabloID identifies Stablo                                                  */
/* 	"Opis_ID" : Stablo ima Opis                                                               */
/* 	"Roditelj_ID" : Stablo roditelj Stablo                                                    */
/* 	"Nivo" : Stablo nivo tinyint                                                              */
/* 	"Sort" : Stablo sort smallint                                                             */
/* 	"TipCvora_ID" : Stablo ima TipCvora                                                       */  
create table "Stablo" ( 
	"Stablo_ID" int not null,
	"Opis_ID" int not null,
	"Roditelj_ID" int null,
	"Nivo" tinyint not null,
	"Sort" smallint not null,
	"TipCvora_ID" tinyint not null) ON 'PRIMARY'  

go

alter table "Stablo"
	add constraint "Stablo_PK" primary key clustered ("Stablo_ID")   


go

/* Create new table "Proizvodjac".                                                            */
/* "Proizvodjac" : Table of Proizvodjac                                                       */
/* 	"Proizvodjac_ID" : ProizvodjacID identifies Proizvodjac                                   */
/* 	"Naziv" : Proizvodjac naziv je Nvarchar(100)                                              */  
create table "Proizvodjac" ( 
	"Proizvodjac_ID" smallint not null,
	"Naziv" nvarchar(100) not null) ON 'PRIMARY'  

go

alter table "Proizvodjac"
	add constraint "Proizvodjac_PK" primary key clustered ("Proizvodjac_ID")   


go

/* Create new table "Motor".                                                                  */
/* "Motor" : Table of Motor                                                                   */
/* 	"Motor_ID" : MotorID identifies Motor                                                     */
/* 	"Oznaka" : Motor oznaka motora je Varchar(100)                                            */
/* 	"Proizvodjac_ID" : Motor proizvodi Proizvodjac                                            */
/* 	"ProizvodnjaOd" : Motor pocela proizvodnja int                                            */
/* 	"ProizvodnjaDo" : Motor zavrsena proizvodnja int                                          */
/* 	"SnagaKwKodObrtajaUMinutiOd" : Motor snaga [kw] kod o/min od smallint                     */
/* 	"SnagaKwKodObrtajaUMinutiDo" : Motor snaga [kw] kod o/min do smallint                     */
/* 	"ObrtajaUMinutiKodSnageKwOd" : Motor snaga kw kod [o/min] od smallint                     */
/* 	"ObrtajaUMinutiKodSnageKwDo" : Motor snaga kw kod [o/min] do smallint                     */
/* 	"ObrtniMomenatKodObrtajaUMinutiOd" : Motor momenat obrtaja [nm] kod o/min od smallint     */
/* 	"ObrtajaUMinutiKodObrtnogMomentaOd" : Motor momenat obrtaja nm kod [o/min] od smallint    */
/* 	"ObrtniMomenatKodObrtajaUMinutiDo" : Motor momenat obrtaja [nm] kod o/min do smallint     */
/* 	"ObrtajaUMinutiKodObrtnogMomentaDo" : Motor momenat obrtaja nm kod [o/min] do smallint    */
/* 	"SnagaKSOd" : Motor ks do smallint                                                        */
/* 	"SnagaKSDo" : Motor ks od smallint                                                        */
/* 	"ZapreminaCcmOd" : Motor ccm od int                                                       */
/* 	"ZapreminaCcmDo" : Motor ccm do int                                                       */
/* 	"Cilindara" : Motor cilindara tinyint                                                     */
/* 	"PrecnikCilindra" : Motor precnik cilindra decimal(6;3)                                   */
/* 	"OblikGlaveCilindra_Opis" : Motor oblik glave cilindra Opis                               */
/* 	"Korak" : Motor korak decimal(6;3)                                                        */
/* 	"BrojLezajevaKolenastogVratilaRadilice" : Motor broj lezajeva kolenastog vratila (radilice) tinyint */
/* 	"KompresijaOd" : Motor kompresija od decimal(6;3)                                         */
/* 	"KompresijaDo" : Motor kompresija do decimal(6;3)                                         */
/* 	"Ventila" : Motor ventila tinyint                                                         */
/* 	"UpravljanjeVentilima_Opis" : Motor upravljanje ventilima Opis                            */
/* 	"VrstaMotora_Opis" : Motor vrsta motora Opis                                              */
/* 	"VrstaGoriva_Opis" : Motor vrsta goriva Opis                                              */
/* 	"PripremaGoriva_Opis" : Motor priprema goriva Opis                                        */
/* 	"PunjenjeKompresija_Opis" : Motor punjenje/kompresija Opis                                */
/* 	"StandardIzduvnihGasova_Opis" : Motor standard za izduvne gasove Opis                     */
/* 	"UpravljanjeMotorom_Opis" : Motor upravljanje motorom Opis                                */
/* 	"OblikBlokaMotora_Opis" : Motor oblik bloka motora Opis                                   */
/* 	"VrstaHladjenja_Opis" : Motor vrsta hladjenja Opis                                        */  
create table "Motor" ( 
	"Motor_ID" smallint not null,
	"Oznaka" varchar(100) not null,
	"Proizvodjac_ID" smallint not null,
	"ProizvodnjaOd" int null,
	"ProizvodnjaDo" int null,
	"SnagaKwKodObrtajaUMinutiOd" smallint null,
	"SnagaKwKodObrtajaUMinutiDo" smallint null,
	"ObrtajaUMinutiKodSnageKwOd" smallint null,
	"ObrtajaUMinutiKodSnageKwDo" smallint null,
	"ObrtniMomenatKodObrtajaUMinutiOd" smallint null,
	"ObrtajaUMinutiKodObrtnogMomentaOd" smallint null,
	"ObrtniMomenatKodObrtajaUMinutiDo" smallint null,
	"ObrtajaUMinutiKodObrtnogMomentaDo" smallint null,
	"SnagaKSOd" smallint null,
	"SnagaKSDo" smallint null,
	"ZapreminaCcmOd" int null,
	"ZapreminaCcmDo" int null,
	"Cilindara" tinyint null,
	"PrecnikCilindra" decimal(6,3) null,
	"OblikGlaveCilindra_Opis" int null,
	"Korak" decimal(6,3) null,
	"BrojLezajevaKolenastogVratilaRadilice" tinyint null,
	"KompresijaOd" decimal(6,3) null,
	"KompresijaDo" decimal(6,3) null,
	"Ventila" tinyint null,
	"UpravljanjeVentilima_Opis" int null,
	"VrstaMotora_Opis" int null,
	"VrstaGoriva_Opis" int null,
	"PripremaGoriva_Opis" int null,
	"PunjenjeKompresija_Opis" int null,
	"StandardIzduvnihGasova_Opis" int null,
	"UpravljanjeMotorom_Opis" int null,
	"OblikBlokaMotora_Opis" int null,
	"VrstaHladjenja_Opis" int null) ON 'PRIMARY'  

go

alter table "Motor"
	add constraint "Motor_PK" primary key clustered ("Motor_ID")   


go

/* Create new table "Kriterijum".                                                             */
/* "Kriterijum" : Table of Kriterijum                                                         */
/* 	"Kriterijum_ID" : KriterijumID identifies Kriterijum                                      */
/* 	"Opis_ID" : Kriterijum kompletan opis Opis                                                */  
create table "Kriterijum" ( 
	"Kriterijum_ID" smallint not null,
	"Opis_ID" int not null) ON 'PRIMARY'  

go

alter table "Kriterijum"
	add constraint "Kriterijum_PK" primary key clustered ("Kriterijum_ID")   


go

/* Create new table "Artikal".                                                                */
/* "Artikal" : Table of Artikal                                                               */
/* 	"Artikal_ID" : ArtikalID identifies Artikal                                               */
/* 	"Opis_ID" : Artikal naziv je Opis                                                         */
/* 	"BrojProizvodjaca" : Artikal broj proizvodjaca je Varchar(100)                            */
/* 	"Proizvodjac_ID" : Proizvodjac has Artikal                                                */  
create table "Artikal" ( 
	"Artikal_ID" int not null,
	"Opis_ID" int not null,
	"BrojProizvodjaca" varchar(100) not null,
	"Proizvodjac_ID" smallint not null) ON 'PRIMARY'  

go

alter table "Artikal"
	add constraint "Artikal_PK" primary key clustered ("Artikal_ID")   


go

/* Add the remaining keys, constraints and indexes for the table "VrstaBrojaZaPretragu".      */
alter table "VrstaBrojaZaPretragu" add constraint "VrstaBrojaZaPretragu_UC1" unique (
	"Naziv")  


go

/* Add the remaining keys, constraints and indexes for the table "TipAutomobila".             */
alter table "TipAutomobila" add constraint "TipAutomobila_UC1" unique (
	"Opis_ID")  


go

/* Add the remaining keys, constraints and indexes for the table "ModelAutomobila".           */
alter table "ModelAutomobila" add constraint "ModelAutomobila_UC1" unique (
	"Opis_ID")  


go

/* Add the remaining keys, constraints and indexes for the table "TipCvora".                  */
alter table "TipCvora" add constraint "TipCvora_UC1" unique (
	"Naziv")  


go

/* Add the remaining keys, constraints and indexes for the table "Stablo".                    */
alter table "Stablo" add constraint "Stablo_UC1" unique (
	"Sort")  


go

/* Add the remaining keys, constraints and indexes for the table "Artikal".                   */
alter table "Artikal" add constraint "Artikal_UC1" unique (
	"Proizvodjac_ID",
	"BrojProizvodjaca")  


go

/* Add foreign key constraints to table "VezaUgradnjaKriterijum".                             */
alter table "VezaUgradnjaKriterijum"
	add constraint "Opis_VezaUgradnjaKriterijum_FK1" foreign key (
		"Opis_ID")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "VezaUgradnjaKriterijum"
	add constraint "Ugradnja_VezaUgradnjaKriterijum_FK1" foreign key (
		"UgradnjaArtikal_ID",
		"UgradnjaTipAutomobila_ID")
	 references "Ugradnja" (
		"Artikal_ID",
		"TipAutomobila_ID") on update no action on delete no action  

go

alter table "VezaUgradnjaKriterijum"
	add constraint "Kriterijum_VezaUgradnjaKriterijum_FK1" foreign key (
		"Kriterijum_ID")
	 references "Kriterijum" (
		"Kriterijum_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "VezaArtikalKriterijum".                              */
alter table "VezaArtikalKriterijum"
	add constraint "Artikal_VezaArtikalKriterijum_FK1" foreign key (
		"Artikal_ID")
	 references "Artikal" (
		"Artikal_ID") on update no action on delete no action  

go

alter table "VezaArtikalKriterijum"
	add constraint "Kriterijum_VezaArtikalKriterijum_FK1" foreign key (
		"Kriterijum_ID")
	 references "Kriterijum" (
		"Kriterijum_ID") on update no action on delete no action  

go

alter table "VezaArtikalKriterijum"
	add constraint "Opis_VezaArtikalKriterijum_FK1" foreign key (
		"Opis_ID")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "Ugradnja".                                           */
alter table "Ugradnja"
	add constraint "Artikal_Ugradnja_FK1" foreign key (
		"Artikal_ID")
	 references "Artikal" (
		"Artikal_ID") on update no action on delete no action  

go

alter table "Ugradnja"
	add constraint "TipAutomobila_Ugradnja_FK1" foreign key (
		"TipAutomobila_ID")
	 references "TipAutomobila" (
		"TipAutomobila_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "VezaArtikalBrojZaPretragu".                          */
alter table "VezaArtikalBrojZaPretragu"
	add constraint "Artikal_VezaArtikalBrojZaPretragu_FK1" foreign key (
		"Artikal_ID")
	 references "Artikal" (
		"Artikal_ID") on update no action on delete no action  

go

alter table "VezaArtikalBrojZaPretragu"
	add constraint "VrstaBrojaZaPretragu_VezaArtikalBrojZaPretragu_FK1" foreign key (
		"VrstaBrojaZaPretragu_ID")
	 references "VrstaBrojaZaPretragu" (
		"VrstaBrojaZaPretragu_ID") on update no action on delete no action  

go

alter table "VezaArtikalBrojZaPretragu"
	add constraint "Proizvodjac_VezaArtikalBrojZaPretragu_FK1" foreign key (
		"Proizvodjac_ID")
	 references "Proizvodjac" (
		"Proizvodjac_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "VezaArtikalStablo".                                  */
alter table "VezaArtikalStablo"
	add constraint "Artikal_VezaArtikalStablo_FK1" foreign key (
		"Artikal_ID")
	 references "Artikal" (
		"Artikal_ID") on update no action on delete no action  

go

alter table "VezaArtikalStablo"
	add constraint "Stablo_VezaArtikalStablo_FK1" foreign key (
		"Stablo_ID")
	 references "Stablo" (
		"Stablo_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "TipAutomobila".                                      */
alter table "TipAutomobila"
	add constraint "ModelAutomobila_TipAutomobila_FK1" foreign key (
		"ModelAutomobila_ID")
	 references "ModelAutomobila" (
		"ModelAutomobila_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK1" foreign key (
		"Opis_ID")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK2" foreign key (
		"NaponAkumulatora_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK3" foreign key (
		"ASR_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK4" foreign key (
		"VrstaMotora_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK5" foreign key (
		"VrstaKocnica_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK6" foreign key (
		"VrstaGoriva_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK7" foreign key (
		"VrstaKatalizatora_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK8" foreign key (
		"VrstaKaroserije_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK9" foreign key (
		"VrstaPogona_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK10" foreign key (
		"Menjac_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK11" foreign key (
		"PripremaGoriva_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK12" foreign key (
		"ABS_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "TipAutomobila"
	add constraint "Opis_TipAutomobila_FK13" foreign key (
		"KocioniSistem_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "ModelAutomobila".                                    */
alter table "ModelAutomobila"
	add constraint "Opis_ModelAutomobila_FK1" foreign key (
		"Opis_ID")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "ModelAutomobila"
	add constraint "Proizvodjac_ModelAutomobila_FK1" foreign key (
		"Proizvodjac_ID")
	 references "Proizvodjac" (
		"Proizvodjac_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "VezaTipAutomobilaMotor".                             */
alter table "VezaTipAutomobilaMotor"
	add constraint "TipAutomobila_VezaTipAutomobilaMotor_FK1" foreign key (
		"TipAutomobila_ID")
	 references "TipAutomobila" (
		"TipAutomobila_ID") on update no action on delete no action  

go

alter table "VezaTipAutomobilaMotor"
	add constraint "Motor_VezaTipAutomobilaMotor_FK1" foreign key (
		"Motor_ID")
	 references "Motor" (
		"Motor_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "Stablo".                                             */
alter table "Stablo"
	add constraint "TipCvora_Stablo_FK1" foreign key (
		"TipCvora_ID")
	 references "TipCvora" (
		"TipCvora_ID") on update no action on delete no action  

go

alter table "Stablo"
	add constraint "Stablo_Stablo_FK1" foreign key (
		"Roditelj_ID")
	 references "Stablo" (
		"Stablo_ID") on update no action on delete no action  

go

alter table "Stablo"
	add constraint "Opis_Stablo_FK1" foreign key (
		"Opis_ID")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "Motor".                                              */
alter table "Motor"
	add constraint "Opis_Motor_FK1" foreign key (
		"OblikBlokaMotora_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK2" foreign key (
		"VrstaGoriva_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK3" foreign key (
		"PripremaGoriva_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK4" foreign key (
		"VrstaMotora_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK5" foreign key (
		"PunjenjeKompresija_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK6" foreign key (
		"StandardIzduvnihGasova_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK7" foreign key (
		"OblikGlaveCilindra_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK8" foreign key (
		"UpravljanjeMotorom_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK9" foreign key (
		"UpravljanjeVentilima_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Opis_Motor_FK10" foreign key (
		"VrstaHladjenja_Opis")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Motor"
	add constraint "Proizvodjac_Motor_FK1" foreign key (
		"Proizvodjac_ID")
	 references "Proizvodjac" (
		"Proizvodjac_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "Kriterijum".                                         */
alter table "Kriterijum"
	add constraint "Opis_Kriterijum_FK1" foreign key (
		"Opis_ID")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

/* Add foreign key constraints to table "Artikal".                                            */
alter table "Artikal"
	add constraint "Opis_Artikal_FK1" foreign key (
		"Opis_ID")
	 references "Opis" (
		"Opis_ID") on update no action on delete no action  

go

alter table "Artikal"
	add constraint "Proizvodjac_Artikal_FK1" foreign key (
		"Proizvodjac_ID")
	 references "Proizvodjac" (
		"Proizvodjac_ID") on update no action on delete no action  

go


/* This is the end of the Microsoft Visual Studio generated SQL DDL script.                   */
